-- coreui (bundled for loadstring) — generated by bundle.py, do not edit by hand.
-- build: 2026-06-16 02:39:28 ae4427c-dirty
print("[coreui] build 2026-06-16 02:39:28 ae4427c-dirty loaded")
local __modules, __cache = {}, {}
local function __require(k)
    local c = __cache[k]; if c then return c[1] end
    local f = __modules[k]; if not f then error('coreui: missing module '..k, 2) end
    local v = f(); __cache[k] = { v }; return v
end

__modules[''] = function()
--!strict
-- coreui — a reusable dark-theme Roblox UI component library.
--
--   local coreui = require(path.to.coreui)
--   local Window = coreui:CreateWindow({ Title = "coreui", Subtitle = "kit", Version = "v1" })
--   local Tab    = Window:CreateTab({ Name = "Home", Icon = "home" })
--   local Group  = Tab:CreateGroup({ Title = "Profile", Column = 1 })
--   Group:Toggle({ Name = "Enable", Default = true, Callback = function(on) end })
--
-- See the component modules under components/ for each control's options.

local Window = __require("components.Window")

local coreui = {}

function coreui:CreateWindow(options: any?)
	return Window(options)
end

return coreui

end

__modules['Icons'] = function()
--!strict
-- Icons.lua — name → Lucide vector icon.
--
-- The reference keys icons by short names ("home", "gear", "chev"…). Lucide
-- ships them as solid white glyphs packed into spritesheets; `LucideData.luau`
-- maps each Lucide name to {assetId, {w,h}, {offX,offY}}. We use the "48px"
-- set (plenty for 14–34px UI icons, far lighter than "256px") and translate
-- our short names through ALIAS. Because the glyphs are white on transparent,
-- `ImageColor3` recolors them freely — text_dim for inactive, white for active.

local Create = __require("util.Create")
local Theme = __require("Theme")
local LucideData = __require("LucideData")

local SET = LucideData["48px"]

-- our short name → Lucide name
local ALIAS: { [string]: string } = {
	home   = "home",        cursor = "mouse-pointer",
	input  = "text-cursor-input", list = "list",
	palette = "palette",    layers = "layers",
	bug    = "bug",         person = "user",
	gear   = "settings",    search = "search",
	min    = "minus",       max    = "square",
	close  = "x",           chev   = "chevron-up",
	caret  = "chevron-down", ddchev = "chevron-down",
	check  = "check",       avatar = "circle-user",
}

-- Unicode fallbacks for any name with no Lucide entry (keeps the UI legible
-- if a name is misspelled or the data file is swapped out).
local GLYPH: { [string]: string } = {
	home = "⌂", layers = "▤", cursor = "➤", input = "⌨", list = "≣",
	palette = "◑", person = "☺", gear = "⚙", search = "⌕", avatar = "☻",
	min = "—", max = "▢", close = "✕", chev = "⌄", caret = "⌄", check = "✓",
}

local Icons = {}

local function entryFor(name: string)
	return SET[ALIAS[name] or name]
end

-- Build an icon instance sized `size`, tinted `color`. Returns an ImageLabel
-- when the icon resolves, otherwise a glyph TextLabel fallback.
function Icons.new(name: string, size: number, color: Color3): GuiObject
	local entry = entryFor(name)
	if entry then
		return Create("ImageLabel", {
			Name = "Icon",
			BackgroundTransparency = 1,
			Size = UDim2.fromOffset(size, size),
			Image = "rbxassetid://" .. entry[1],
			ImageRectSize = Vector2.new(entry[2][1], entry[2][2]),
			ImageRectOffset = Vector2.new(entry[3][1], entry[3][2]),
			ImageColor3 = color,
			ScaleType = Enum.ScaleType.Stretch,
		})
	end
	return Create("TextLabel", {
		Name = "Icon",
		BackgroundTransparency = 1,
		Size = UDim2.fromOffset(size, size),
		Text = GLYPH[name] or "•",
		TextColor3 = color,
		TextSize = size,
		Font = Theme.Font.Medium,
		TextXAlignment = Enum.TextXAlignment.Center,
		TextYAlignment = Enum.TextYAlignment.Center,
	})
end

-- Apply an icon onto an existing ImageLabel/ImageButton (matches the design's
-- `Icons.apply` helper). No-op for unknown names.
function Icons.apply(image: ImageLabel | ImageButton, name: string)
	local entry = entryFor(name)
	if not entry then
		return
	end
	image.Image = "rbxassetid://" .. entry[1]
	image.ImageRectSize = Vector2.new(entry[2][1], entry[2][2])
	image.ImageRectOffset = Vector2.new(entry[3][1], entry[3][2])
end

-- Tint an icon regardless of whether it resolved to an ImageLabel or a glyph.
function Icons.tint(icon: GuiObject, color: Color3)
	if icon:IsA("ImageLabel") or icon:IsA("ImageButton") then
		icon.ImageColor3 = color
	elseif icon:IsA("TextLabel") then
		icon.TextColor3 = color
	end
end

return Icons

end

__modules['LucideData'] = function()
-- @generated by bundle.py (tree-shaken from the full Lucide set).
--!nocheck

return {["48px"]={["chevron-down"]={16898612819,{48,48},{196,918}},["chevron-up"]={16898612819,{48,48},{710,918}},["circle-user"]={16898613044,{48,48},{869,257}},["mouse-pointer"]={16898613613,{48,48},{612,869}},["text-cursor-input"]={16898613869,{48,48},{771,563}},bug={16898612819,{48,48},{257,967}},check={16898612819,{48,48},{710,869}},home={16898613509,{48,48},{820,147}},layers={16898613509,{48,48},{98,967}},list={16898613509,{48,48},{869,808}},minus={16898613613,{48,48},{771,196}},palette={16898613613,{48,48},{453,918}},search={16898613699,{48,48},{918,857}},settings={16898613777,{48,48},{771,257}},square={16898613777,{48,48},{869,710}},user={16898613869,{48,48},{661,869}},x={16898613869,{48,48},{869,906}}}}

end

__modules['Theme'] = function()
--!strict
-- Theme.lua — design tokens (colors, metrics, fonts).
-- Values mirror reference/coreui.css 1:1. Offset pixels map directly to Roblox.

local Theme = {}

-- ── Colors ────────────────────────────────────────────────────────────────
Theme.Colors = {
	bg          = Color3.fromHex("0C0C0E"), -- window body
	chrome      = Color3.fromHex("131315"), -- titlebar / sidebar / status bar
	card        = Color3.fromHex("161618"), -- group card fill
	pop         = Color3.fromHex("18181B"), -- dropdown / colorpicker / toast
	control     = Color3.fromHex("1B1B1F"), -- input / dropdown / button fill
	control_hi  = Color3.fromHex("232328"), -- hovered control
	toggle_off  = Color3.fromHex("2C2C31"), -- toggle track (off) + slider track
	knob        = Color3.fromHex("D6D6DB"), -- toggle knob (off)
	border      = Color3.fromHex("262629"), -- card / control borders, dividers
	border_soft = Color3.fromHex("1F1F22"), -- between-field dividers
	text        = Color3.fromHex("EDEDF0"), -- primary text
	text_muted  = Color3.fromHex("8C8C94"), -- secondary text / descriptions
	text_dim    = Color3.fromHex("5F5F67"), -- placeholders, inactive icons, chevrons
	accent      = Color3.fromHex("F2680C"), -- active nav, toggle-on, accent button, focus
	accent_2    = Color3.fromHex("FF8A3D"), -- accent hover / gradient top
	white       = Color3.fromHex("FFFFFF"),
	danger      = Color3.fromHex("FF6B6B"), -- close-button hover
}

-- ── Metrics (offset px) ───────────────────────────────────────────────────
Theme.Metrics = {
	windowWidth   = 780,
	windowHeight  = 560,
	windowRadius  = 12,
	titlebar      = 50,
	statusbar     = 34,
	sidebar       = 64,
	navButton     = 40,
	navRadius     = 11,
	navIcon       = 20,
	cardRadius    = 9,
	controlRadius = 7,
	columnGap     = 24,
	groupGap      = 18,
}

-- ── Fonts ─────────────────────────────────────────────────────────────────
-- UI font "Inter" → Gotham family. Mono (keybind/hex) → Roboto Mono.
--
-- These are FontFace objects (set via the `FontFace` property, NOT `Font`).
-- The legacy `Enum.Font.*` values render from fixed-size bitmap atlases —
-- Roblox scales the nearest baked size to your TextSize, which is what made
-- the text look soft / rough / "pixelated". FontFace uses the SDF text
-- renderer, so glyphs stay crisp at any size.
local GOTHAM = "rbxasset://fonts/families/GothamSSm.json"
Theme.Font = {
	Bold    = Font.new(GOTHAM, Enum.FontWeight.Bold),                          -- titles
	Medium  = Font.new(GOTHAM, Enum.FontWeight.Medium),                        -- labels / weighted text
	Regular = Font.new(GOTHAM, Enum.FontWeight.Regular),                       -- body
	Mono    = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular), -- keybind / hex
}

return Theme

end

__modules['components.Button'] = function()
--!strict
-- components/Button.lua — single button (bare or titled) + side-by-side ButtonRow.

local Create = __require("util.Create")
local Theme = __require("Theme")
local Tween = __require("util.Tween")
local Field = __require("components.Field")

local function newButton(ctx: any, label: string, accent: boolean, callback: (() -> ())?): TextButton
	local colors = Theme.Colors
	local btn = Create("TextButton", {
		Name = "Button",
		AutoButtonColor = false,
		Size = UDim2.new(1, 0, 0, 36),
		BackgroundColor3 = accent and ctx.Accent or colors.control,
		Text = label or "Button",
		TextColor3 = accent and colors.white or colors.text,
		TextSize = 13,
		FontFace = Theme.Font.Medium,
	}, {
		Create.corner(Theme.Metrics.controlRadius),
		Create.stroke(accent and colors.accent or colors.border, 1),
		Create("UIScale", {}),
	})
	local stroke = btn:FindFirstChildOfClass("UIStroke") :: UIStroke
	if accent then
		stroke.Transparency = 1
	end
	local scale = btn:FindFirstChildOfClass("UIScale") :: UIScale

	local hovering = false
	local function base(): Color3
		return accent and ctx.Accent or colors.control
	end
	local function over(): Color3
		return accent and ctx.AccentHover or colors.control_hi
	end
	btn.MouseEnter:Connect(function()
		hovering = true
		Tween.play(btn, Tween.Fast, { BackgroundColor3 = over() })
	end)
	btn.MouseLeave:Connect(function()
		hovering = false
		Tween.play(btn, Tween.Fast, { BackgroundColor3 = base() })
	end)
	btn.Activated:Connect(function()
		-- quick squash-and-release so the tap feels physical
		scale.Scale = 0.96
		Tween.play(scale, Tween.Spring, { Scale = 1 })
		if callback then
			callback()
		end
	end)

	if accent then
		ctx:RegisterAccent(function()
			btn.BackgroundColor3 = hovering and over() or base()
		end)
	end
	return btn
end

local Button = {}

function Button.single(ctx: any, opts: any)
	-- titled → stacked field; bare → standalone padded row
	if opts.Name or opts.Desc then
		local f = Field.new(ctx, opts, true)
		local btn = newButton(ctx, opts.Label, opts.Accent == true, opts.Callback)
		btn.LayoutOrder = 2
		btn.Parent = f.field
		return f.field, { element = btn }, true
	end

	local wrap = Create("Frame", {
		Name = "ButtonRow",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
	}, {
		Create.padding(8, 2),
	})
	local btn = newButton(ctx, opts.Label, opts.Accent == true, opts.Callback)
	btn.Parent = wrap
	return wrap, { element = btn }, true
end

function Button.row(ctx: any, list: { any })
	local wrap = Create("Frame", {
		Name = "ButtonRow",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
	}, {
		Create.padding(8, 2),
		Create.listLayout({
			FillDirection = Enum.FillDirection.Horizontal,
			Padding = UDim.new(0, 10),
		}),
	})
	local GAP = 10
	local n = #list
	for i, item in list do
		local btn = newButton(ctx, item.Label, item.Accent == true, item.Callback)
		btn.LayoutOrder = i
		-- Even split without flexbox: each button takes 1/n of the row, minus
		-- its share of the inter-button gaps.
		btn.Size = UDim2.new(1 / n, -(GAP * (n - 1)) / n, 0, 36)
		btn.Parent = wrap
	end
	return wrap, {}, true
end

return Button

end

__modules['components.Colorpicker'] = function()
--!strict
-- components/Colorpicker.lua — swatch button + preset grid popover with hex.

local Create = __require("util.Create")
local Theme = __require("Theme")
local Tween = __require("util.Tween")
local Field = __require("components.Field")

local DEFAULT_PRESETS = {
	"f2680c", "ff5757", "ffb020", "34c759", "2dd4bf", "3b82f6",
	"8b5cf6", "ec4899", "ededf0", "8c8c94", "3a3a3e", "161618",
}

local function toHex(color: Color3): string
	return ("#%02X%02X%02X"):format(
		math.round(color.R * 255),
		math.round(color.G * 255),
		math.round(color.B * 255)
	)
end

return function(ctx: any, opts: any)
	local colors = Theme.Colors
	local f = Field.new(ctx, opts)
	local value: Color3 = opts.Default or Color3.fromHex("f2680c")

	local swatch = Create("TextButton", {
		Name = "Colorpicker",
		AutoButtonColor = false,
		Text = "",
		Size = UDim2.fromOffset(30, 30),
		BackgroundColor3 = value,
		LayoutOrder = 2,
		Parent = f.row,
	}, {
		Create.corner(8),
		Create.stroke(colors.border),
	})

	local menu = Create("CanvasGroup", {
		Name = "ColorMenu",
		Visible = false,
		Size = UDim2.fromOffset(168, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundColor3 = colors.pop,
	}, {
		Create.corner(10),
		Create.stroke(colors.border),
		Create.padding(10),
		Create.listLayout({ Padding = UDim.new(0, 9) }),
	})

	local grid = Create("Frame", {
		Name = "Grid",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		LayoutOrder = 1,
		Parent = menu,
	}, {
		Create("UIGridLayout", {
			CellSize = UDim2.fromOffset(19, 19),
			CellPadding = UDim2.fromOffset(6, 6),
			SortOrder = Enum.SortOrder.LayoutOrder,
		}),
	})

	local hexLabel = Create("TextLabel", {
		Name = "Hex",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, 0, 0, 14),
		Text = toHex(value),
		TextColor3 = colors.text_muted,
		TextSize = 12,
		FontFace = Theme.Font.Mono,
		TextXAlignment = Enum.TextXAlignment.Left,
		LayoutOrder = 2,
		Parent = menu,
	})

	local function apply(color: Color3)
		value = color
		Tween.play(swatch, Tween.Normal, { BackgroundColor3 = color })
		hexLabel.Text = toHex(color)
		if opts.Callback then
			opts.Callback(color)
		end
	end

	for i, hex in (opts.Presets or DEFAULT_PRESETS) do
		local chip = Create("TextButton", {
			Name = "Chip" .. i,
			AutoButtonColor = false,
			Text = "",
			BackgroundColor3 = Color3.fromHex(hex),
			LayoutOrder = i,
			Parent = grid,
		}, {
			Create.corner(6),
			Create("UIStroke", { Color = colors.white, Transparency = 0.9 }),
			Create("UIScale", {}),
		})
		local chipScale = chip:FindFirstChildOfClass("UIScale") :: UIScale
		chip.MouseEnter:Connect(function()
			Tween.play(chipScale, Tween.Spring, { Scale = 1.18 })
		end)
		chip.MouseLeave:Connect(function()
			Tween.play(chipScale, Tween.Fast, { Scale = 1 })
		end)
		chip.Activated:Connect(function()
			apply(chip.BackgroundColor3)
			ctx:ClosePopover()
		end)
	end

	swatch.Activated:Connect(function()
		if ctx:IsOpen(menu) then
			ctx:ClosePopover()
		else
			ctx:OpenPopover(menu, swatch)
		end
	end)

	local handle = {}
	function handle:Get(): Color3
		return value
	end
	function handle:Set(color: Color3)
		apply(color)
	end

	return f.field, handle, true
end

end

__modules['components.Controls'] = function()
--!strict
-- components/Controls.lua — the control surface shared by Group cards and
-- Sections. Owns the container, dispatches to component builders, and manages
-- the 1px "between-field" separators (drawn after every bordered item except
-- the last, mirroring the CSS `:last-child` border rule).

local Create = __require("util.Create")
local Theme = __require("Theme")

local Toggle = __require("components.Toggle")
local Slider = __require("components.Slider")
local Dropdown = __require("components.Dropdown")
local Input = __require("components.Input")
local Keybind = __require("components.Keybind")
local Colorpicker = __require("components.Colorpicker")
local Button = __require("components.Button")
local Paragraph = __require("components.Paragraph")
local Label = __require("components.Label")
local Divider = __require("components.Divider")
local List = __require("components.List")
local Player = __require("components.Player")
local Section = __require("components.Section")

local Controls = {}

function Controls.new(ctx: any, frame: Frame)
	local items: { { inst: Instance, sep: Frame?, bordered: boolean } } = {}
	local count = 0

	local function refresh()
		local n = #items
		for i, entry in items do
			if entry.sep then
				entry.sep.Visible = entry.bordered and i < n
			end
		end
	end

	local function place(inst: Instance, bordered: boolean)
		count += 1
		;(inst :: any).LayoutOrder = count * 2
		inst.Parent = frame

		local sep: Frame? = nil
		if bordered then
			sep = Create("Frame", {
				Name = "Separator",
				Size = UDim2.new(1, 0, 0, 1),
				BackgroundColor3 = Theme.Colors.border_soft,
				BorderSizePixel = 0,
				LayoutOrder = count * 2 + 1,
				Parent = frame,
			})
		end
		table.insert(items, { inst = inst, sep = sep, bordered = bordered })
		refresh()
	end

	-- Build via a component, drop it in, hand back the control's handle.
	local function mount(builder: (any, any) -> (Instance, any, boolean), opts: any): any
		local inst, handle, bordered = builder(ctx, opts)
		place(inst, bordered)
		return handle
	end

	local api = {}

	function api:Toggle(o) return mount(Toggle, o) end
	function api:Slider(o) return mount(Slider, o) end
	function api:Input(o) return mount(Input, o) end
	function api:Keybind(o) return mount(Keybind, o) end
	function api:Colorpicker(o) return mount(Colorpicker, o) end
	function api:Paragraph(o) return mount(Paragraph, o) end
	function api:Label(o) return mount(Label, o) end
	function api:Divider() return mount(Divider, {}) end
	function api:Player(o) return mount(Player, o) end
	function api:List(o) return mount(List, o) end

	function api:Dropdown(o)
		return mount(function(c, opts)
			return Dropdown(c, opts, false)
		end, o)
	end
	function api:MultiDropdown(o)
		return mount(function(c, opts)
			return Dropdown(c, opts, true)
		end, o)
	end

	function api:Button(o)
		local inst, handle, bordered = Button.single(ctx, o)
		place(inst, bordered)
		return handle
	end
	function api:ButtonRow(list)
		local inst, handle, bordered = Button.row(ctx, list)
		place(inst, bordered)
		return handle
	end

	function api:Section(o)
		local section, body = Section(ctx, o)
		place(section, true)
		return Controls.new(ctx, body)
	end

	return api
end

return Controls

end

__modules['components.Divider'] = function()
--!strict
-- components/Divider.lua — a hairline with 6px breathing room above/below.

local Create = __require("util.Create")
local Theme = __require("Theme")

return function(ctx: any, _opts: any)
	local holder = Create("Frame", {
		Name = "Divider",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, 0, 0, 13),
	}, {
		Create("Frame", {
			Name = "Line",
			AnchorPoint = Vector2.new(0.5, 0.5),
			Position = UDim2.fromScale(0.5, 0.5),
			Size = UDim2.new(1, 0, 0, 1),
			BackgroundColor3 = Theme.Colors.border_soft,
			BorderSizePixel = 0,
		}),
	})
	-- The divider is itself the separating line → no managed bottom border.
	return holder, {}, false
end

end

__modules['components.Dropdown'] = function()
--!strict
-- components/Dropdown.lua — single + multi select.
-- Box is a TextButton; the menu lives in the window overlay (high ZIndex) so it
-- escapes the scrolling content's clip. Single sets + closes; multi toggles a
-- check per option and stays open. Outside click closes (Context popover).

local Create = __require("util.Create")
local Theme = __require("Theme")
local Tween = __require("util.Tween")
local Icons = __require("Icons")
local Field = __require("components.Field")

local function hover(button: GuiButton, base: Color3, over: Color3)
	button.MouseEnter:Connect(function()
		Tween.play(button, Tween.Fast, { BackgroundColor3 = over })
	end)
	button.MouseLeave:Connect(function()
		Tween.play(button, Tween.Fast, { BackgroundColor3 = base })
	end)
end

local function build(ctx: any, opts: any, multi: boolean)
	local colors = Theme.Colors
	local options = opts.Options or {}
	local placeholder = opts.Placeholder or "None"
	local stack = opts.Stack == true

	local single: string? = opts.Default
	local selected: { [string]: boolean } = {}
	if multi and type(opts.Default) == "table" then
		for _, v in opts.Default do
			selected[v] = true
		end
	end

	local f = Field.new(ctx, opts, stack)

	-- box ────────────────────────────────────────────────────────────────────
	local box = Create("TextButton", {
		Name = "Dropdown",
		AutoButtonColor = false,
		Text = "",
		Size = stack and UDim2.new(1, 0, 0, 32) or UDim2.fromOffset(opts.Width or 130, 32),
		BackgroundColor3 = colors.control,
		LayoutOrder = 2,
		Parent = stack and f.field or f.row,
	}, {
		Create.corner(Theme.Metrics.controlRadius),
		Create.stroke(colors.border),
		Create.padding(0, 8, 0, 12),
		-- No UIListLayout: a layout-managed child won't render its Rotation, so
		-- the caret is positioned manually to keep it free to spin.
	})
	local boxStroke = box:FindFirstChildOfClass("UIStroke") :: UIStroke

	local valLabel = Create("TextLabel", {
		Name = "Value",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, -24, 1, 0), -- fills, leaving 10px gap + 14px chevron
		AutomaticSize = Enum.AutomaticSize.None,
		Text = placeholder,
		TextColor3 = colors.text_muted,
		TextSize = 13,
		FontFace = Theme.Font.Regular,
		TextXAlignment = Enum.TextXAlignment.Left,
		TextTruncate = Enum.TextTruncate.AtEnd,
		Parent = box,
	})

	local chevron = Icons.new("caret", 14, colors.text_dim)
	chevron.AnchorPoint = Vector2.new(1, 0.5)
	chevron.Position = UDim2.new(1, 0, 0.5, 0);
	(chevron :: any).Parent = box

	-- menu ─────────────────────────────────────────────────────────────────── (parented to overlay on open)
	local menu = Create("CanvasGroup", {
		Name = "DropdownMenu",
		Visible = false,
		AutomaticSize = Enum.AutomaticSize.Y,
		Size = UDim2.fromOffset(150, 0),
		BackgroundColor3 = colors.pop,
		ClipsDescendants = true,
	}, {
		Create.corner(8),
		Create.stroke(colors.border),
		Create.padding(5),
		Create.listLayout({ Padding = UDim.new(0, 2) }),
		Create("UISizeConstraint", { MaxSize = Vector2.new(math.huge, 210) }),
	})

	local function valueLabelText(): (string, boolean)
		if multi then
			local list = {}
			for _, opt in options do
				if selected[opt] then
					table.insert(list, opt)
				end
			end
			if #list == 0 then
				return placeholder, false
			end
			return table.concat(list, ", "), true
		else
			if single == nil then
				return placeholder, false
			end
			return single, true
		end
	end

	local function relabel()
		local text, hasVal = valueLabelText()
		valLabel.Text = text
		valLabel.TextColor3 = hasVal and colors.text or colors.text_muted
	end

	local function isSelected(opt: string): boolean
		if multi then
			return selected[opt] == true
		end
		return single == opt
	end

	local rebuild -- fwd
	local function fireMulti(): { string }
		local list = {}
		for _, opt in options do
			if selected[opt] then
				table.insert(list, opt)
			end
		end
		return list
	end

	rebuild = function()
		for _, child in menu:GetChildren() do
			if child:IsA("TextButton") then
				child:Destroy()
			end
		end
		for i, opt in options do
			local sel = isSelected(opt)
			local optBtn = Create("TextButton", {
				Name = opt,
				AutoButtonColor = false,
				Text = "",
				BackgroundColor3 = colors.control_hi,
				BackgroundTransparency = 1,
				AutomaticSize = Enum.AutomaticSize.Y,
				Size = UDim2.new(1, 0, 0, 0),
				LayoutOrder = i,
				Parent = menu,
			}, {
				Create.corner(6),
				Create.padding(7, 9),
				Create.listLayout({
					FillDirection = Enum.FillDirection.Horizontal,
					VerticalAlignment = Enum.VerticalAlignment.Center,
					Padding = UDim.new(0, 9),
				}),
			})

			local tickHolder = Create("Frame", {
				Name = "Tick",
				BackgroundTransparency = 1,
				Size = UDim2.fromOffset(15, 15),
				LayoutOrder = 1,
				Parent = optBtn,
			})
			local tick = Icons.new("check", 14, ctx.Accent)
			tick.Visible = sel;
			(tick :: any).Parent = tickHolder

			Create("TextLabel", {
				Name = "Label",
				BackgroundTransparency = 1,
				AutomaticSize = Enum.AutomaticSize.X,
				Size = UDim2.new(0, 0, 0, 16),
				Text = opt,
				TextColor3 = sel and colors.text or colors.text_muted,
				TextSize = 13,
				FontFace = Theme.Font.Regular,
				TextXAlignment = Enum.TextXAlignment.Left,
				LayoutOrder = 2,
				Parent = optBtn,
			})

			optBtn.MouseEnter:Connect(function()
				Tween.play(optBtn, Tween.Fast, { BackgroundTransparency = 0 })
			end)
			optBtn.MouseLeave:Connect(function()
				Tween.play(optBtn, Tween.Fast, { BackgroundTransparency = 1 })
			end)
			optBtn.Activated:Connect(function()
				if multi then
					selected[opt] = not selected[opt] or nil
					relabel()
					rebuild()
					if opts.Callback then
						opts.Callback(fireMulti())
					end
				else
					single = opt
					relabel()
					ctx:ClosePopover()
					if opts.Callback then
						opts.Callback(single)
					end
				end
			end)
		end
	end

	local function setOpenVisual(open: boolean)
		Tween.play(boxStroke, Tween.Fast, { Color = open and ctx.Accent or colors.border })
		Tween.play(chevron, Tween.Spin, { Rotation = open and 180 or 0 })
	end

	box.Activated:Connect(function()
		if ctx:IsOpen(menu) then
			ctx:ClosePopover()
			return
		end
		rebuild()
		menu.Size = UDim2.fromOffset(math.max(box.AbsoluteSize.X, 150), 0)
		setOpenVisual(true)
		ctx:OpenPopover(menu, box, function()
			setOpenVisual(false)
		end)
	end)
	hover(box, colors.control, colors.control_hi)

	ctx:RegisterAccent(function() end) -- ticks/box read ctx.Accent live on open
	relabel()

	local handle = {}
	function handle:Get(): any
		if multi then
			return fireMulti()
		end
		return single
	end
	function handle:Set(value: any)
		if multi then
			selected = {}
			if type(value) == "table" then
				for _, v in value do
					selected[v] = true
				end
			end
		else
			single = value
		end
		relabel()
		if opts.Callback then
			opts.Callback(multi and fireMulti() or single)
		end
	end

	return f.field, handle, true
end

return build

end

__modules['components.Field'] = function()
--!strict
-- components/Field.lua — the row scaffold every control sits on.
--
-- Layout mirrors `.coreui-field` from the CSS: 10px vertical padding, a flex
-- row with a name/description block on the left and the control on the right.
-- "Stacked" fields (slider, input, full-width dropdown/button) drop the control
-- to its own full-width line below the row.

local Create = __require("util.Create")
local Theme = __require("Theme")

local Field = {}

export type Field = {
	field: Frame, -- the whole field (parent for stacked controls)
	row: Frame,   -- the name | control row (parent for inline controls)
	main: Frame?, -- the name/description block, if a Name was given
}

function Field.new(ctx: any, opts: { Name: string?, Desc: string? }, stack: boolean?): Field
	local colors = Theme.Colors

	local field = Create("Frame", {
		Name = "Field",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
	}, {
		Create.padding(10, 2),
		Create.listLayout({ Padding = UDim.new(0, 9) }),
	})

	local ROW_GAP = 14
	local row = Create("Frame", {
		Name = "Row",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		LayoutOrder = 1,
		Parent = field,
	}, {
		Create.listLayout({
			FillDirection = Enum.FillDirection.Horizontal,
			VerticalAlignment = Enum.VerticalAlignment.Center,
			Padding = UDim.new(0, ROW_GAP),
		}),
	})

	local main: Frame? = nil
	if opts.Name then
		local block = Create("Frame", {
			Name = "Main",
			BackgroundTransparency = 1,
			Size = UDim2.new(0, 0, 0, 0),
			AutomaticSize = Enum.AutomaticSize.Y,
			LayoutOrder = 1,
			Parent = row,
		}, {
			Create.listLayout({ Padding = UDim.new(0, 3) }),
		})

		Create("TextLabel", {
			Name = "Title",
			BackgroundTransparency = 1,
			Size = UDim2.new(1, 0, 0, 0),
			AutomaticSize = Enum.AutomaticSize.Y,
			Text = opts.Name,
			TextColor3 = colors.text,
			TextSize = 13,
			FontFace = Theme.Font.Regular,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextYAlignment = Enum.TextYAlignment.Top,
			TextWrapped = true,
			LayoutOrder = 1,
			Parent = block,
		})

		if opts.Desc then
			Create("TextLabel", {
				Name = "Desc",
				BackgroundTransparency = 1,
				Size = UDim2.new(1, 0, 0, 0),
				AutomaticSize = Enum.AutomaticSize.Y,
				Text = opts.Desc,
				TextColor3 = colors.text_muted,
				TextSize = 12,
				FontFace = Theme.Font.Regular,
				TextXAlignment = Enum.TextXAlignment.Left,
				TextYAlignment = Enum.TextYAlignment.Top,
				TextWrapped = true,
				LineHeight = 1.1,
				LayoutOrder = 2,
				Parent = block,
			})
		end
		main = block

		-- No flexbox: the label block consumes the row's leftover width so the
		-- control (added by the caller into `row`) lands flush right. Width is
		-- the row minus every sibling's measured width and the gap to each.
		local function syncMain()
			local used, others = 0, 0
			for _, child in row:GetChildren() do
				if child:IsA("GuiObject") and child ~= block then
					used += child.AbsoluteSize.X
					others += 1
				end
			end
			local avail = row.AbsoluteSize.X - used - others * ROW_GAP
			block.Size = UDim2.new(0, math.max(0, avail), 0, 0)
		end
		row:GetPropertyChangedSignal("AbsoluteSize"):Connect(syncMain)
		row.ChildAdded:Connect(function(child)
			if child:IsA("GuiObject") then
				child:GetPropertyChangedSignal("AbsoluteSize"):Connect(syncMain)
			end
			task.defer(syncMain)
		end)
		task.defer(syncMain)
	end

	return { field = field, row = row, main = main }
end

return Field

end

__modules['components.Group'] = function()
--!strict
-- components/Group.lua — titled card with a collapsible body.
-- Header toggles the card's visibility; the card hosts the control surface.

local Create = __require("util.Create")
local Theme = __require("Theme")
local Tween = __require("util.Tween")
local Icons = __require("Icons")
local Controls = __require("components.Controls")

return function(ctx: any, column: Frame, opts: any)
	local colors = Theme.Colors
	local collapsed = opts.Collapsed == true

	local group = Create("Frame", {
		Name = "Group",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		Parent = column,
	}, {
		Create.listLayout({}),
	})

	-- NOTE: the header does NOT use a UIListLayout. A UIListLayout manages its
	-- children's transforms and suppresses their Rotation, so a chevron laid out
	-- by one never visually spins. Title + chevron are positioned manually so the
	-- chevron is free to rotate (matches a bare ImageLabel, which rotates fine).
	local head = Create("TextButton", {
		Name = "Head",
		AutoButtonColor = false,
		Text = "",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		LayoutOrder = 1,
		Parent = group,
	}, {
		Create.padding(2, 4, 8, 4),
	})

	Create("TextLabel", {
		Name = "Title",
		BackgroundTransparency = 1,
		AutomaticSize = Enum.AutomaticSize.Y,
		Size = UDim2.new(1, -18, 0, 0), -- leaves room for the chevron flush right
		Text = opts.Title or "Group",
		TextColor3 = colors.text_muted,
		TextSize = 13,
		FontFace = Theme.Font.Medium,
		TextXAlignment = Enum.TextXAlignment.Left,
		Parent = head,
	})

	local chevron = Icons.new("chev", 14, colors.text_dim)
	chevron.AnchorPoint = Vector2.new(1, 0.5)
	chevron.Position = UDim2.new(1, 0, 0.5, 0)
	chevron.Rotation = collapsed and 180 or 0;
	(chevron :: any).Parent = head

	local card = Create("Frame", {
		Name = "Card",
		BackgroundColor3 = colors.card,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		Visible = not collapsed,
		LayoutOrder = 2,
		Parent = group,
	}, {
		Create.corner(Theme.Metrics.cardRadius),
		Create.stroke(colors.border),
		Create.padding(2, 14),
		Create.listLayout({}),
	})

	head.Activated:Connect(function()
		collapsed = not collapsed
		-- Spin the chevron; reveal the card on expand, hide it once the spin
		-- has played on collapse so the rotation reads before it vanishes.
		Tween.play(chevron, Tween.Spin, { Rotation = collapsed and 180 or 0 })
		if collapsed then
			task.delay(0.12, function()
				if collapsed then
					card.Visible = false
				end
			end)
		else
			card.Visible = true
		end
	end)

	return Controls.new(ctx, card)
end

end

__modules['components.Input'] = function()
--!strict
-- components/Input.lua — full-width 36px TextBox, accent stroke on focus.

local Create = __require("util.Create")
local Theme = __require("Theme")
local Tween = __require("util.Tween")
local Field = __require("components.Field")

return function(ctx: any, opts: any)
	local colors = Theme.Colors
	local f = Field.new(ctx, opts, true)

	local box = Create("TextBox", {
		Name = "Input",
		Size = UDim2.new(1, 0, 0, 36),
		BackgroundColor3 = colors.control,
		Text = opts.Default or "",
		PlaceholderText = opts.Placeholder or "",
		PlaceholderColor3 = colors.text_dim,
		TextColor3 = colors.text,
		TextSize = 13,
		FontFace = Theme.Font.Regular,
		TextXAlignment = Enum.TextXAlignment.Left,
		ClearTextOnFocus = false,
		ClipsDescendants = true,
		LayoutOrder = 2,
		Parent = f.field,
	}, {
		Create.corner(Theme.Metrics.controlRadius),
		Create.stroke(colors.border),
		Create.padding(0, 12),
	})
	local stroke = box:FindFirstChildOfClass("UIStroke") :: UIStroke

	box.Focused:Connect(function()
		Tween.play(stroke, Tween.Fast, { Color = ctx.Accent })
	end)
	box.FocusLost:Connect(function(enterPressed)
		Tween.play(stroke, Tween.Fast, { Color = colors.border })
		if enterPressed and opts.OnEnter then
			opts.OnEnter(box.Text)
		end
	end)
	box:GetPropertyChangedSignal("Text"):Connect(function()
		if opts.Callback then
			opts.Callback(box.Text)
		end
	end)

	local handle = {}
	function handle:Get(): string
		return box.Text
	end
	function handle:Set(value: string)
		box.Text = value
	end

	return f.field, handle, true
end

end

__modules['components.Keybind'] = function()
--!strict
-- components/Keybind.lua — click to listen, capture the next key pressed.

local UserInputService = game:GetService("UserInputService")

local Create = __require("util.Create")
local Theme = __require("Theme")
local Field = __require("components.Field")

return function(ctx: any, opts: any)
	local colors = Theme.Colors
	local f = Field.new(ctx, opts)
	local key: Enum.KeyCode = opts.Default or Enum.KeyCode.Unknown
	local listening = false

	local button = Create("TextButton", {
		Name = "Keybind",
		AutoButtonColor = false,
		AutomaticSize = Enum.AutomaticSize.X,
		Size = UDim2.fromOffset(70, 32),
		BackgroundColor3 = colors.control,
		Text = key ~= Enum.KeyCode.Unknown and key.Name or "None",
		TextColor3 = colors.text,
		TextSize = 12,
		FontFace = Theme.Font.Mono,
		LayoutOrder = 2,
		Parent = f.row,
	}, {
		Create.corner(Theme.Metrics.controlRadius),
		Create.stroke(colors.border),
		Create.padding(0, 14),
		Create("UISizeConstraint", { MinSize = Vector2.new(70, 32) }),
	})
	local stroke = button:FindFirstChildOfClass("UIStroke") :: UIStroke

	button.Activated:Connect(function()
		if listening then
			return
		end
		listening = true
		button.Text = "..."
		button.TextColor3 = ctx.Accent
		stroke.Color = ctx.Accent

		local conn: RBXScriptConnection
		conn = UserInputService.InputBegan:Connect(function(input)
			if input.UserInputType ~= Enum.UserInputType.Keyboard then
				return
			end
			conn:Disconnect()
			key = input.KeyCode
			listening = false
			button.Text = key.Name
			button.TextColor3 = colors.text
			stroke.Color = colors.border
			if opts.Callback then
				opts.Callback(key)
			end
		end)
	end)

	local handle = {}
	function handle:Get(): Enum.KeyCode
		return key
	end
	function handle:Set(value: Enum.KeyCode)
		key = value
		button.Text = key ~= Enum.KeyCode.Unknown and key.Name or "None"
		if opts.Callback then
			opts.Callback(key)
		end
	end

	return f.field, handle, true
end

end

__modules['components.Label'] = function()
--!strict
-- components/Label.lua — key / value row; handle :Set(v) updates the value.

local Create = __require("util.Create")
local Theme = __require("Theme")

return function(ctx: any, opts: any)
	local colors = Theme.Colors

	local row = Create("Frame", {
		Name = "Label",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
	}, {
		Create.padding(9, 2),
	})

	Create("TextLabel", {
		Name = "Key",
		BackgroundTransparency = 1,
		AutomaticSize = Enum.AutomaticSize.XY,
		Position = UDim2.fromScale(0, 0),
		Text = opts.Key or "",
		TextColor3 = colors.text_muted,
		TextSize = 13,
		FontFace = Theme.Font.Regular,
		TextXAlignment = Enum.TextXAlignment.Left,
		Parent = row,
	})

	local valueLabel = Create("TextLabel", {
		Name = "Value",
		BackgroundTransparency = 1,
		AutomaticSize = Enum.AutomaticSize.XY,
		AnchorPoint = Vector2.new(1, 0),
		Position = UDim2.fromScale(1, 0),
		Text = opts.Value or "",
		TextColor3 = colors.text,
		TextSize = 13,
		FontFace = Theme.Font.Medium,
		TextXAlignment = Enum.TextXAlignment.Right,
		Parent = row,
	})

	local handle = {}
	function handle:Set(value: string)
		valueLabel.Text = value
	end

	return row, handle, true
end

end

__modules['components.List'] = function()
--!strict
-- components/List.lua — bullet list. Items: { Name?, Value?, Text?, Dim? }.

local Create = __require("util.Create")
local Theme = __require("Theme")

return function(ctx: any, items: { any })
	local colors = Theme.Colors

	local list = Create("Frame", {
		Name = "List",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
	}, {
		Create.padding(6, 2),
		Create.listLayout({ Padding = UDim.new(0, 2) }),
	})

	for i, item in items or {} do
		local dim = item.Dim == true
		local dotColor = dim and colors.text_dim or colors.text_muted

		local li = Create("Frame", {
			Name = "Item",
			BackgroundTransparency = 1,
			Size = UDim2.new(1, 0, 0, 0),
			AutomaticSize = Enum.AutomaticSize.Y,
			LayoutOrder = i,
			Parent = list,
		}, {
			Create.listLayout({
				FillDirection = Enum.FillDirection.Horizontal,
				VerticalAlignment = Enum.VerticalAlignment.Top,
				Padding = UDim.new(0, 9),
			}),
		})

		Create("Frame", {
			Name = "Dot",
			BackgroundColor3 = dotColor,
			Size = UDim2.fromOffset(4, 4),
			Position = UDim2.fromOffset(3, 6),
			LayoutOrder = 1,
			Parent = li,
		}, { Create.corner(999) })

		local text: string
		if item.Name then
			text = item.Name .. ":  " .. (item.Value or "")
		else
			text = item.Text or ""
		end

		Create("TextLabel", {
			Name = "Text",
			BackgroundTransparency = 1,
			AutomaticSize = Enum.AutomaticSize.Y,
			Size = UDim2.new(1, -13, 0, 0),
			Text = text,
			TextColor3 = dim and colors.text_dim or colors.text_muted,
			TextSize = 13,
			FontFace = Theme.Font.Regular,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextYAlignment = Enum.TextYAlignment.Top,
			TextWrapped = true,
			LayoutOrder = 2,
			Parent = li,
		})
	end

	return list, {}, false
end

end

__modules['components.Notify'] = function()
--!strict
-- components/Notify.lua — bottom-right toast. Slides + fades in (0.22s), holds
-- for `Duration` (default 3.2s), slides out (0.25s), then destroys itself.

local Create = __require("util.Create")
local Theme = __require("Theme")
local Tween = __require("util.Tween")

return function(ctx: any, container: Frame, opts: any)
	local colors = Theme.Colors
	opts = opts or {}

	-- CanvasGroup → fade every descendant at once; renders to its own buffer
	-- so the inner card's horizontal slide is clipped (no layout reflow).
	local order = (container:GetAttribute("count") or 0) + 1
	container:SetAttribute("count", order)

	local toast = Create("CanvasGroup", {
		Name = "Toast",
		BackgroundTransparency = 1,
		Size = UDim2.fromOffset(240, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		GroupTransparency = 1,
		LayoutOrder = order,
		Parent = container,
	})

	local card = Create("Frame", {
		Name = "Card",
		Position = UDim2.fromOffset(20, 0),
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundColor3 = colors.pop,
		ClipsDescendants = true,
		Parent = toast,
	}, {
		Create.corner(9),
		Create.stroke(colors.border),
	})

	-- content holds the vertical text stack; the card sizes to it. The accent
	-- bar is positioned absolutely (height tracked) so it never feeds the
	-- card's AutomaticSize — otherwise its (1,0) height would run away.
	local content = Create("Frame", {
		Name = "Content",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		Parent = card,
	}, {
		Create.padding(10, 13, 10, 16),
		Create.listLayout({ Padding = UDim.new(0, 3) }),
	})

	local bar = Create("Frame", {
		Name = "AccentBar",
		Position = UDim2.fromOffset(0, 0),
		Size = UDim2.fromOffset(3, 0),
		BackgroundColor3 = ctx.Accent,
		BorderSizePixel = 0,
		ZIndex = 2,
		Parent = card,
	})
	content:GetPropertyChangedSignal("AbsoluteSize"):Connect(function()
		bar.Size = UDim2.fromOffset(3, content.AbsoluteSize.Y)
	end)
	ctx:RegisterAccent(function(accent)
		bar.BackgroundColor3 = accent
	end)

	if opts.Title then
		Create("TextLabel", {
			Name = "Title",
			BackgroundTransparency = 1,
			Size = UDim2.new(1, 0, 0, 0),
			AutomaticSize = Enum.AutomaticSize.Y,
			Text = opts.Title,
			TextColor3 = colors.text,
			TextSize = 13,
			FontFace = Theme.Font.Medium,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextWrapped = true,
			LayoutOrder = 1,
			Parent = content,
		})
	end

	Create("TextLabel", {
		Name = "Text",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		Text = opts.Text or "",
		TextColor3 = colors.text_muted,
		TextSize = 12,
		FontFace = Theme.Font.Regular,
		TextXAlignment = Enum.TextXAlignment.Left,
		TextYAlignment = Enum.TextYAlignment.Top,
		TextWrapped = true,
		LayoutOrder = 2,
		Parent = content,
	})

	-- in
	Tween.play(toast, Tween.Toast, { GroupTransparency = 0 })
	Tween.play(card, Tween.Toast, { Position = UDim2.fromOffset(0, 0) })

	-- hold → out → destroy
	task.delay(opts.Duration or 3.2, function()
		Tween.play(card, Tween.ToastOut, { Position = UDim2.fromOffset(20, 0) })
		local out = Tween.play(toast, Tween.ToastOut, { GroupTransparency = 1 })
		out.Completed:Once(function()
			toast:Destroy()
		end)
	end)
end

end

__modules['components.Paragraph'] = function()
--!strict
-- components/Paragraph.lua — optional title + body copy.

local Create = __require("util.Create")
local Theme = __require("Theme")

return function(ctx: any, opts: any)
	local colors = Theme.Colors

	local p = Create("Frame", {
		Name = "Paragraph",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
	}, {
		Create.padding(11, 2),
		Create.listLayout({ Padding = UDim.new(0, 5) }),
	})

	if opts.Title then
		Create("TextLabel", {
			Name = "Title",
			BackgroundTransparency = 1,
			Size = UDim2.new(1, 0, 0, 0),
			AutomaticSize = Enum.AutomaticSize.Y,
			Text = opts.Title,
			TextColor3 = colors.text,
			TextSize = 13,
			FontFace = Theme.Font.Medium,
			TextXAlignment = Enum.TextXAlignment.Left,
			TextWrapped = true,
			LayoutOrder = 1,
			Parent = p,
		})
	end

	Create("TextLabel", {
		Name = "Body",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		Text = opts.Body or "",
		TextColor3 = colors.text_muted,
		TextSize = 12,
		FontFace = Theme.Font.Regular,
		TextXAlignment = Enum.TextXAlignment.Left,
		TextYAlignment = Enum.TextYAlignment.Top,
		TextWrapped = true,
		LineHeight = 1.3,
		LayoutOrder = 2,
		Parent = p,
	})

	return p, {}, true
end

end

__modules['components.Player'] = function()
--!strict
-- components/Player.lua — avatar + name/badge + @username · ID info panel.

local Create = __require("util.Create")
local Theme = __require("Theme")
local Icons = __require("Icons")

return function(ctx: any, opts: any)
	local colors = Theme.Colors

	local panel = Create("Frame", {
		Name = "Player",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
	}, {
		Create.padding(12, 2),
		Create.listLayout({
			FillDirection = Enum.FillDirection.Horizontal,
			VerticalAlignment = Enum.VerticalAlignment.Center,
			Padding = UDim.new(0, 14),
		}),
	})

	-- avatar ───────────────────────────────────────────────────────────────
	local avatar = Create("Frame", {
		Name = "Avatar",
		Size = UDim2.fromOffset(56, 56),
		BackgroundColor3 = colors.accent,
		ClipsDescendants = true,
		LayoutOrder = 1,
		Parent = panel,
	}, {
		Create.corner(14),
		Create.stroke(Color3.fromRGB(255, 255, 255):Lerp(colors.accent, 0.88)),
	})
	local gradient = Create("UIGradient", {
		Color = ColorSequence.new(colors.accent_2, colors.accent),
		Rotation = 135,
		Parent = avatar,
	})

	if opts.Avatar then
		Create("ImageLabel", {
			Name = "Image",
			BackgroundTransparency = 1,
			Size = UDim2.fromScale(1, 1),
			Image = opts.Avatar,
			ScaleType = Enum.ScaleType.Crop,
			Parent = avatar,
		})
	else
		local icon = Icons.new("avatar", 34, colors.white)
		icon.AnchorPoint = Vector2.new(0.5, 0.5)
		icon.Position = UDim2.fromScale(0.5, 0.5);
		(icon :: any).Parent = avatar
	end

	-- info ─────────────────────────────────────────────────────────────────
	local info = Create("Frame", {
		Name = "Info",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, -70, 0, 0), -- fills past the 56px avatar + 14px gap
		AutomaticSize = Enum.AutomaticSize.Y,
		LayoutOrder = 2,
		Parent = panel,
	}, {
		Create.listLayout({ Padding = UDim.new(0, 2) }),
	})

	local nameRow = Create("Frame", {
		Name = "NameRow",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		LayoutOrder = 1,
		Parent = info,
	}, {
		Create.listLayout({
			FillDirection = Enum.FillDirection.Horizontal,
			VerticalAlignment = Enum.VerticalAlignment.Center,
			Padding = UDim.new(0, 8),
		}),
	})

	Create("TextLabel", {
		Name = "Name",
		BackgroundTransparency = 1,
		AutomaticSize = Enum.AutomaticSize.XY,
		Text = opts.DisplayName or opts.Username or "Player",
		TextColor3 = colors.text,
		TextSize = 16,
		FontFace = Theme.Font.Medium,
		TextXAlignment = Enum.TextXAlignment.Left,
		LayoutOrder = 1,
		Parent = nameRow,
	})

	local badge: TextLabel? = nil
	if opts.Badge then
		badge = Create("TextLabel", {
			Name = "Badge",
			AutomaticSize = Enum.AutomaticSize.X,
			Size = UDim2.fromOffset(0, 16),
			BackgroundTransparency = 1,
			Text = string.upper(opts.Badge),
			TextColor3 = colors.accent,
			TextSize = 10,
			FontFace = Theme.Font.Bold,
			LayoutOrder = 2,
			Parent = nameRow,
		}, {
			Create.corner(999),
			Create.stroke(colors.accent),
			Create.padding(1, 6),
		})
	end

	local sub = "@" .. (opts.Username or "player")
	if opts.UserId and opts.UserId ~= 0 then
		sub = sub .. "  ·  ID " .. tostring(opts.UserId)
	end
	Create("TextLabel", {
		Name = "Sub",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		Text = sub,
		TextColor3 = colors.text_muted,
		TextSize = 12,
		FontFace = Theme.Font.Regular,
		TextXAlignment = Enum.TextXAlignment.Left,
		LayoutOrder = 2,
		Parent = info,
	})

	ctx:RegisterAccent(function(accent, accentHover)
		avatar.BackgroundColor3 = accent
		gradient.Color = ColorSequence.new(accentHover, accent)
		if badge then
			badge.TextColor3 = accent
			local badgeStroke = badge:FindFirstChildOfClass("UIStroke")
			if badgeStroke then
				badgeStroke.Color = accent
			end
		end
	end)

	return panel, {}, false
end

end

__modules['components.Section'] = function()
--!strict
-- components/Section.lua — a nested collapsible group (indented, left rule).
-- Returns the section frame plus the inner body that controls mount into.

local Create = __require("util.Create")
local Theme = __require("Theme")
local Tween = __require("util.Tween")
local Icons = __require("Icons")

return function(ctx: any, opts: any): (Frame, Frame)
	local colors = Theme.Colors
	local collapsed = opts.Collapsed == true

	local section = Create("Frame", {
		Name = "Section",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
	}, {
		Create.listLayout({}),
	})

	-- No UIListLayout on the header: a layout-managed child won't render its
	-- Rotation, so the chevron is positioned manually to keep it free to spin.
	local head = Create("TextButton", {
		Name = "Head",
		AutoButtonColor = false,
		Text = "",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		LayoutOrder = 1,
		Parent = section,
	}, {
		Create.padding(9, 2),
	})

	Create("TextLabel", {
		Name = "Title",
		BackgroundTransparency = 1,
		AutomaticSize = Enum.AutomaticSize.Y,
		Size = UDim2.new(1, -18, 0, 0), -- leaves room for the chevron flush right
		Text = opts.Title or "Section",
		TextColor3 = colors.text,
		TextSize = 13,
		FontFace = Theme.Font.Medium,
		TextXAlignment = Enum.TextXAlignment.Left,
		Parent = head,
	})

	local chevron = Icons.new("chev", 14, colors.text_dim)
	chevron.AnchorPoint = Vector2.new(1, 0.5)
	chevron.Position = UDim2.new(1, 0, 0.5, 0)
	chevron.Rotation = collapsed and 180 or 0;
	(chevron :: any).Parent = head

	local bodyWrap = Create("Frame", {
		Name = "BodyWrap",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		Visible = not collapsed,
		LayoutOrder = 2,
		Parent = section,
	})

	local body = Create("Frame", {
		Name = "Body",
		BackgroundTransparency = 1,
		Position = UDim2.fromOffset(14, 0),
		Size = UDim2.new(1, -14, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		Parent = bodyWrap,
	}, {
		Create.padding(1, 0, 8, 0),
		Create.listLayout({}),
	})

	-- left rule, height tracked to the body so AutomaticSize stays stable.
	local rule = Create("Frame", {
		Name = "Rule",
		Position = UDim2.fromOffset(2, 1),
		Size = UDim2.fromOffset(1, 0),
		BackgroundColor3 = colors.border,
		BorderSizePixel = 0,
		Parent = bodyWrap,
	})
	body:GetPropertyChangedSignal("AbsoluteSize"):Connect(function()
		rule.Size = UDim2.fromOffset(1, body.AbsoluteSize.Y)
	end)

	head.Activated:Connect(function()
		collapsed = not collapsed
		Tween.play(chevron, Tween.Spin, { Rotation = collapsed and 180 or 0 })
		if collapsed then
			task.delay(0.12, function()
				if collapsed then
					bodyWrap.Visible = false
				end
			end)
		else
			bodyWrap.Visible = true
		end
	end)

	return section, body
end

end

__modules['components.Slider'] = function()
--!strict
-- components/Slider.lua — 6px pill track, accent fill, 15px white knob.
-- Live drag via UserInputService (no tween), clamped + stepped.

local UserInputService = game:GetService("UserInputService")

local Create = __require("util.Create")
local Theme = __require("Theme")
local Tween = __require("util.Tween")
local Field = __require("components.Field")

local function clamp(v: number, a: number, b: number): number
	return math.max(a, math.min(b, v))
end

local function format(v: number, suffix: string): string
	return ("%g"):format(v) .. suffix
end

return function(ctx: any, opts: any)
	local colors = Theme.Colors
	local min = opts.Min or 0
	local max = opts.Max or 100
	local step = opts.Step or 1
	local suffix = opts.Suffix or ""
	local value = clamp(opts.Default or min, min, max)

	local f = Field.new(ctx, opts, true)

	local valBox = Create("TextLabel", {
		Name = "Value",
		AutomaticSize = Enum.AutomaticSize.X,
		Size = UDim2.fromOffset(38, 22),
		BackgroundColor3 = colors.control,
		Text = format(value, suffix),
		TextColor3 = colors.text_muted,
		TextSize = 12,
		FontFace = Theme.Font.Medium,
		LayoutOrder = 2,
		Parent = f.row,
	}, {
		Create.corner(6),
		Create.stroke(colors.border),
		Create.padding(2, 9),
		Create("UISizeConstraint", { MinSize = Vector2.new(38, 22) }),
	})

	local track = Create("TextButton", {
		Name = "Slider",
		AutoButtonColor = false,
		Text = "",
		Size = UDim2.new(1, 0, 0, 6),
		BackgroundColor3 = colors.toggle_off,
		LayoutOrder = 2,
		Parent = f.field,
	}, {
		Create.corner(999),
	})

	local fill = Create("Frame", {
		Name = "Fill",
		Size = UDim2.fromScale(0, 1),
		BackgroundColor3 = ctx.Accent,
		Parent = track,
	}, {
		Create.corner(999),
	})

	local knob = Create("Frame", {
		Name = "Knob",
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.fromScale(0, 0.5),
		Size = UDim2.fromOffset(15, 15),
		BackgroundColor3 = colors.white,
		ZIndex = 2,
		Parent = track,
	}, {
		Create.corner(999),
		Create("UIScale", {}),
	})
	local knobScale = knob:FindFirstChildOfClass("UIScale") :: UIScale

	local function render()
		local pct = (value - min) / (max - min)
		fill.Size = UDim2.fromScale(pct, 1)
		knob.Position = UDim2.fromScale(pct, 0.5)
		valBox.Text = format(value, suffix)
	end

	local function setFromX(x: number)
		local pct = clamp((x - track.AbsolutePosition.X) / track.AbsoluteSize.X, 0, 1)
		local raw = min + pct * (max - min)
		value = clamp(math.round(raw / step) * step, min, max)
		render()
		if opts.Callback then
			opts.Callback(value)
		end
	end

	local dragging = false
	track.InputBegan:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.MouseButton1
			or input.UserInputType == Enum.UserInputType.Touch then
			dragging = true
			Tween.play(knobScale, Tween.Spring, { Scale = 1.3 }) -- grow while grabbed
			setFromX(input.Position.X)
		end
	end)
	UserInputService.InputChanged:Connect(function(input)
		if dragging and (input.UserInputType == Enum.UserInputType.MouseMovement
			or input.UserInputType == Enum.UserInputType.Touch) then
			setFromX(input.Position.X)
		end
	end)
	UserInputService.InputEnded:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.MouseButton1
			or input.UserInputType == Enum.UserInputType.Touch then
			if dragging then
				Tween.play(knobScale, Tween.Spring, { Scale = 1 }) -- settle back on release
			end
			dragging = false
		end
	end)

	ctx:RegisterAccent(function(accent)
		fill.BackgroundColor3 = accent
	end)
	render()

	local handle = {}
	function handle:Get(): number
		return value
	end
	function handle:Set(v: number)
		value = clamp(v, min, max)
		render()
		if opts.Callback then
			opts.Callback(value)
		end
	end

	return f.field, handle, true
end

end

__modules['components.Tab'] = function()
--!strict
-- components/Tab.lua — a sidebar nav button + a two-column content page.

local Create = __require("util.Create")
local Theme = __require("Theme")
local Tween = __require("util.Tween")
local Icons = __require("Icons")
local Group = __require("components.Group")

local M = Theme.Metrics

local function newColumn(order: number): Frame
	return Create("Frame", {
		Name = "Column",
		BackgroundTransparency = 1,
		AnchorPoint = order == 2 and Vector2.new(1, 0) or Vector2.new(0, 0),
		Position = order == 2 and UDim2.fromScale(1, 0) or UDim2.fromScale(0, 0),
		Size = UDim2.new(0.5, -(M.columnGap / 2), 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
	}, {
		Create.listLayout({ Padding = UDim.new(0, M.groupGap) }),
	})
end

return function(ctx: any, opts: any)
	local colors = Theme.Colors

	-- nav button ──────────────────────────────────────────────────────────
	local button = Create("TextButton", {
		Name = "Nav_" .. (opts.Name or "Tab"),
		AutoButtonColor = false,
		Text = "",
		Size = UDim2.fromOffset(M.navButton, M.navButton),
		BackgroundColor3 = colors.accent,
		BackgroundTransparency = 1,
	}, {
		Create.corner(M.navRadius),
	})

	-- Accent glow under the active button — the CSS `box-shadow: 0 6px 16px -4px
	-- accent`. A soft accent-tinted shadow image sitting behind the button
	-- (ZIndex 0, so the overflow haloes out past the button's rounded fill).
	local glow = Create("ImageLabel", {
		Name = "Glow",
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.fromScale(0.5, 0.62),
		Size = UDim2.fromOffset(M.navButton + 26, M.navButton + 26),
		BackgroundTransparency = 1,
		Image = "rbxassetid://6014261993",
		ImageColor3 = ctx.Accent,
		ImageTransparency = 1,
		ScaleType = Enum.ScaleType.Slice,
		SliceCenter = Rect.new(49, 49, 450, 450),
		ZIndex = 0,
		Parent = button,
	})

	local icon = Icons.new(opts.Icon or "gear", M.navIcon, colors.text_dim)
	icon.AnchorPoint = Vector2.new(0.5, 0.5)
	icon.Position = UDim2.fromScale(0.5, 0.5);
	(icon :: any).Parent = button
	local iconScale = Create("UIScale", { Parent = icon })

	-- content page ────────────────────────────────────────────────────────
	local page = Create("Frame", {
		Name = "Page_" .. (opts.Name or "Tab"),
		BackgroundTransparency = 1,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		Visible = false,
	})
	local columns = Create("Frame", {
		Name = "Columns",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		Parent = page,
	})
	local col1 = newColumn(1)
	col1.Parent = columns
	local col2 = newColumn(2)
	col2.Parent = columns

	local divider = Create("Frame", {
		Name = "ColDivider",
		AnchorPoint = Vector2.new(0.5, 0),
		Position = UDim2.fromScale(0.5, 0),
		Size = UDim2.fromOffset(1, 0),
		BackgroundColor3 = colors.border_soft,
		BorderSizePixel = 0,
		Parent = columns,
	})
	columns:GetPropertyChangedSignal("AbsoluteSize"):Connect(function()
		divider.Size = UDim2.fromOffset(1, columns.AbsoluteSize.Y)
	end)

	-- nav state ──────────────────────────────────────────────────────────
	local active = false
	local hovering = false
	-- Crossfade both colour and transparency in a single tween. The old code
	-- snapped BackgroundColor3 to white instantly while the fill was still
	-- opaque (and snapped transparency to 0 on activate), so a switched-off tab
	-- showed a solid flash for one frame before fading. Keeping the colour on
	-- the accent while the fill fades out means there's no intermediate solid
	-- colour to flash — the accent simply fades in / out.
	local function paint(animate: boolean?)
		local goal
		local glowGoal = { ImageTransparency = active and 0.45 or 1 }
		if active then
			goal = { BackgroundColor3 = ctx.Accent, BackgroundTransparency = 0 }
			Icons.tint(icon, colors.white)
		else
			goal = {
				-- idle (transparency 1) keeps the accent so the fade-out is a
				-- pure accent fade; only the faint hover fill uses white.
				BackgroundColor3 = hovering and colors.white or ctx.Accent,
				BackgroundTransparency = hovering and 0.92 or 1,
			}
			Icons.tint(icon, hovering and colors.text_muted or colors.text_dim)
		end
		if animate == false then
			for key, value in goal do
				(button :: any)[key] = value
			end
			glow.ImageTransparency = glowGoal.ImageTransparency
		else
			Tween.play(button, Tween.Fast, goal)
			Tween.play(glow, Tween.Fast, glowGoal)
		end
	end
	button.MouseEnter:Connect(function()
		hovering = true
		if not active then
			paint()
		end
	end)
	button.MouseLeave:Connect(function()
		hovering = false
		if not active then
			paint()
		end
	end)
	ctx:RegisterAccent(function()
		glow.ImageColor3 = ctx.Accent
		if active then
			button.BackgroundColor3 = ctx.Accent
		end
	end)

	local tab = {
		button = button,
		page = page,
	}
	function tab:_setActive(value: boolean)
		local becameActive = value and not active
		active = value
		page.Visible = value
		paint()
		if becameActive then
			iconScale.Scale = 0.8
			Tween.play(iconScale, Tween.Spring, { Scale = 1 }) -- pop on select
		end
	end
	function tab:CreateGroup(groupOpts: any)
		local target = (groupOpts and groupOpts.Column == 2) and col2 or col1
		return Group(ctx, target, groupOpts or {})
	end

	return tab
end

end

__modules['components.Toggle'] = function()
--!strict
-- components/Toggle.lua — 42×23 pill, 17px knob, +19px travel.

local Create = __require("util.Create")
local Theme = __require("Theme")
local Tween = __require("util.Tween")
local Field = __require("components.Field")

local OFF_POS = UDim2.fromOffset(3, 3)
local ON_POS = UDim2.fromOffset(22, 3) -- 3 + 19px travel

return function(ctx: any, opts: any)
	local colors = Theme.Colors
	local f = Field.new(ctx, opts)
	local state = opts.Default == true

	local track = Create("TextButton", {
		Name = "Toggle",
		AutoButtonColor = false,
		Text = "",
		Size = UDim2.fromOffset(42, 23),
		BackgroundColor3 = colors.toggle_off,
		LayoutOrder = 2,
		Parent = f.row,
	}, {
		Create.corner(999),
	})

	local knob = Create("Frame", {
		Name = "Knob",
		Size = UDim2.fromOffset(17, 17),
		Position = OFF_POS,
		BackgroundColor3 = colors.knob,
		Parent = track,
	}, {
		Create.corner(999),
	})

	local function paint(animate: boolean)
		local trackColor = state and ctx.Accent or colors.toggle_off
		local knobColor = state and colors.white or colors.knob
		local pos = state and ON_POS or OFF_POS
		if animate then
			Tween.play(track, Tween.Normal, { BackgroundColor3 = trackColor })
			Tween.play(knob, Tween.Normal, { BackgroundColor3 = knobColor })
			Tween.play(knob, Tween.Spring, { Position = pos }) -- slight overshoot on the slide
		else
			track.BackgroundColor3 = trackColor
			knob.BackgroundColor3 = knobColor
			knob.Position = pos
		end
	end

	local handle = {}
	function handle:Get(): boolean
		return state
	end
	function handle:Set(value: boolean)
		state = value == true
		paint(true)
		if opts.Callback then
			opts.Callback(state)
		end
	end

	track.Activated:Connect(function()
		handle:Set(not state)
	end)

	ctx:RegisterAccent(function()
		paint(false)
	end)

	return f.field, handle, true
end

end

__modules['components.Window'] = function()
--!strict
-- components/Window.lua — the window shell: titlebar, sidebar, scrolling content,
-- status bar and overlay. Owns the Context, the tab list, notifications and the
-- live accent. Mounts a ScreenGui to the LocalPlayer's PlayerGui.

local Players = game:GetService("Players")
local RunService = game:GetService("RunService")
local UserInputService = game:GetService("UserInputService")

local Create = __require("util.Create")
local Theme = __require("Theme")
local Tween = __require("util.Tween")
local Icons = __require("Icons")
local Context = __require("util.Context")
local Tab = __require("components.Tab")
local Notify = __require("components.Notify")

local M = Theme.Metrics

return function(opts: any)
	opts = opts or {}
	local colors = Theme.Colors

	-- ── ScreenGui + window frame ────────────────────────────────────────────
	local screenGui = Create("ScreenGui", {
		Name = "coreui",
		IgnoreGuiInset = true,
		ResetOnSpawn = false,
		ZIndexBehavior = Enum.ZIndexBehavior.Sibling,
	})

	-- CanvasGroup (not Frame) so minimize/close can fade the *entire* window as a
	-- single unit via GroupTransparency — a plain Frame can only fade its own
	-- background, which is why scaling-then-hiding looked like a snap.
	local main = Create("CanvasGroup", {
		Name = "Window",
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.fromScale(0.5, 0.5),
		Size = UDim2.fromOffset(M.windowWidth, M.windowHeight),
		BackgroundColor3 = colors.bg,
		ClipsDescendants = true,
		Parent = screenGui,
	}, {
		Create.corner(M.windowRadius),
		Create.stroke(Color3.new(0, 0, 0)),
		Create("UIScale", {}),
	})
	local mainScale = main:FindFirstChildOfClass("UIScale") :: UIScale

	-- ── drop shadow ─────────────────────────────────────────────────────────
	-- The reference window floats: `box-shadow: 0 30px 80px -20px rgba(0,0,0,.8)`.
	-- A 9-sliced soft-shadow image behind the window gives it that elevation. It
	-- lives in the ScreenGui (a sibling behind `main`, not a child — `main`
	-- clips, and the shadow has to bleed past the window edges) and tracks the
	-- window as it's dragged / resized.
	-- A *radial* shadow image (one smooth centre→edge gradient) stretched behind
	-- the window. A 9-slice shadow only softens its ~49px border and stretches a
	-- solid core, so it reads as a hard dark band that ends abruptly — this fades
	-- gradually the whole way out instead. Big PAD = the gradient's soft tail is
	-- what shows past the window edge; the dark middle stays hidden behind it.
	local SHADOW_PAD = 130 -- how far the soft tail bleeds past each edge
	local SHADOW_DROP = 16 -- nudge down so the light reads as coming from above
	local SHADOW_T = 0.6  -- resting image transparency
	local shadow = Create("ImageLabel", {
		Name = "Shadow",
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = main.Position,
		Size = UDim2.fromOffset(M.windowWidth + SHADOW_PAD, M.windowHeight + SHADOW_PAD),
		BackgroundTransparency = 1,
		Image = "rbxassetid://1316045217", -- soft radial blur
		ImageColor3 = Color3.new(0, 0, 0),
		ImageTransparency = 1, -- faded in on mount, alongside the window
		ScaleType = Enum.ScaleType.Stretch,
		ZIndex = 0,
		Parent = screenGui,
	})
	local function syncShadow()
		shadow.Position = main.Position + UDim2.fromOffset(0, SHADOW_DROP)
		shadow.Size = UDim2.new(
			main.Size.X.Scale, main.Size.X.Offset + SHADOW_PAD,
			main.Size.Y.Scale, main.Size.Y.Offset + SHADOW_PAD
		)
	end
	main:GetPropertyChangedSignal("Position"):Connect(syncShadow)
	main:GetPropertyChangedSignal("Size"):Connect(syncShadow)

	-- Never exceed the viewport — on small screens the window shrinks to fit
	-- (centered) instead of spilling content off the right/bottom edge.
	local function fitWindow()
		local vp = screenGui.AbsoluteSize
		if vp.X <= 0 then
			return
		end
		main.Size = UDim2.fromOffset(
			math.min(M.windowWidth, vp.X - 24),
			math.min(M.windowHeight, vp.Y - 24)
		)
	end
	screenGui:GetPropertyChangedSignal("AbsoluteSize"):Connect(fitWindow)
	task.defer(fitWindow)

	-- ── titlebar ───────────────────────────────────────────────────────────
	local titlebar = Create("Frame", {
		Name = "Titlebar",
		Size = UDim2.new(1, 0, 0, M.titlebar),
		BackgroundColor3 = colors.chrome,
		Parent = main,
	}, {
		-- Round the top corners to match the window. main's ClipsDescendants
		-- clips to a rectangle (not the rounded shape), so without this the
		-- square chrome corners poke past main's rounded corners.
		Create.corner(M.windowRadius),
		Create("Frame", { -- square off the bottom so only the top corners round
			Name = "SquareFill",
			AnchorPoint = Vector2.new(0, 1),
			Position = UDim2.fromScale(0, 1),
			Size = UDim2.new(1, 0, 0, M.windowRadius),
			BackgroundColor3 = colors.chrome,
			BorderSizePixel = 0,
		}),
		Create("Frame", { -- bottom hairline
			Name = "Border",
			AnchorPoint = Vector2.new(0, 1),
			Position = UDim2.fromScale(0, 1),
			Size = UDim2.new(1, 0, 0, 1),
			BackgroundColor3 = colors.border_soft,
			BorderSizePixel = 0,
		}),
		Create("Frame", { -- top inset highlight — the CSS `inset` lit edge that
			Name = "Highlight",            -- catches light and lifts the window
			Size = UDim2.new(1, 0, 0, 1),
			BackgroundColor3 = colors.white,
			BackgroundTransparency = 0.94,
			BorderSizePixel = 0,
		}),
	})

	-- logo
	local logo = Create("Frame", {
		Name = "Logo",
		Size = UDim2.fromOffset(26, 26),
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.new(0, M.sidebar / 2, 0.5, 0),
		BackgroundColor3 = colors.accent,
		Parent = titlebar,
	}, {
		Create.corner(8),
	})
	local logoGradient = Create("UIGradient", {
		Color = ColorSequence.new(colors.accent_2, colors.accent),
		Rotation = 135,
		Parent = logo,
	})
	Create("Frame", { -- ring
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.fromScale(0.5, 0.5),
		Size = UDim2.fromOffset(13, 13),
		BackgroundTransparency = 1,
		Parent = logo,
	}, { Create.corner(999), Create.stroke(colors.white, 2) })
	Create("Frame", { -- dot
		AnchorPoint = Vector2.new(0.5, 0.5),
		Position = UDim2.fromScale(0.5, 0.5),
		Size = UDim2.fromOffset(5, 5),
		BackgroundColor3 = colors.white,
		Parent = logo,
	}, { Create.corner(999) })

	Create("TextLabel", {
		Name = "Title",
		BackgroundTransparency = 1,
		Size = UDim2.fromScale(1, 1),
		Text = opts.Title or "coreui",
		TextColor3 = colors.text,
		TextSize = 16,
		FontFace = Theme.Font.Bold,
		Parent = titlebar,
	})

	-- Right cluster holds a collapsible search field followed by the window
	-- buttons; the horizontal list keeps them packed against the right edge.
	local rightCluster = Create("Frame", {
		Name = "RightCluster",
		AnchorPoint = Vector2.new(1, 0.5),
		Position = UDim2.new(1, -18, 0.5, 0),
		Size = UDim2.fromOffset(0, M.titlebar),
		AutomaticSize = Enum.AutomaticSize.X,
		BackgroundTransparency = 1,
		Parent = titlebar,
	}, {
		Create.listLayout({
			FillDirection = Enum.FillDirection.Horizontal,
			VerticalAlignment = Enum.VerticalAlignment.Center,
			Padding = UDim.new(0, 14),
		}),
	})

	-- search field — hidden until the search button is clicked
	local searchField = Create("Frame", {
		Name = "Search",
		Visible = false,
		Size = UDim2.fromOffset(180, 30),
		BackgroundColor3 = colors.control,
		LayoutOrder = 1,
		Parent = rightCluster,
	}, {
		Create.corner(M.controlRadius),
		Create.stroke(colors.border),
		Create.padding(0, 10),
		Create.listLayout({
			FillDirection = Enum.FillDirection.Horizontal,
			VerticalAlignment = Enum.VerticalAlignment.Center,
			Padding = UDim.new(0, 8),
		}),
	})
	local searchIcon = Icons.new("search", 14, colors.text_dim)
	searchIcon.LayoutOrder = 1;
	(searchIcon :: any).Parent = searchField
	local searchBox = Create("TextBox", {
		Name = "Box",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, -22, 1, 0),
		Text = "",
		PlaceholderText = "Search",
		PlaceholderColor3 = colors.text_dim,
		TextColor3 = colors.text,
		TextSize = 13,
		FontFace = Theme.Font.Regular,
		TextXAlignment = Enum.TextXAlignment.Left,
		ClearTextOnFocus = false,
		LayoutOrder = 2,
		Parent = searchField,
	})

	local winButtons = Create("Frame", {
		Name = "WinButtons",
		Size = UDim2.fromOffset(0, M.titlebar),
		AutomaticSize = Enum.AutomaticSize.X,
		BackgroundTransparency = 1,
		LayoutOrder = 2,
		Parent = rightCluster,
	}, {
		Create.listLayout({
			FillDirection = Enum.FillDirection.Horizontal,
			VerticalAlignment = Enum.VerticalAlignment.Center,
			Padding = UDim.new(0, 15),
		}),
	})

	local winBtns: { [string]: TextButton } = {}
	for i, name in { "search", "min", "max", "close" } do
		local btn = Create("TextButton", {
			Name = name,
			AutoButtonColor = false,
			BackgroundTransparency = 1,
			Size = UDim2.fromOffset(16, 16),
			Text = "",
			LayoutOrder = i,
			Parent = winButtons,
		})
		local icon = Icons.new(name, 16, colors.text_muted)
		icon.AnchorPoint = Vector2.new(0.5, 0.5)
		icon.Position = UDim2.fromScale(0.5, 0.5);
		(icon :: any).Parent = btn

		local over = name == "close" and colors.danger or colors.text
		btn.MouseEnter:Connect(function()
			Tween.play(icon, Tween.Fast, { ImageColor3 = over })
		end)
		btn.MouseLeave:Connect(function()
			Tween.play(icon, Tween.Fast, { ImageColor3 = colors.text_muted })
		end)
		winBtns[name] = btn
	end

	-- ── body: sidebar + content ─────────────────────────────────────────────
	local body = Create("Frame", {
		Name = "Body",
		Position = UDim2.fromOffset(0, M.titlebar),
		Size = UDim2.new(1, 0, 1, -(M.titlebar + M.statusbar)),
		BackgroundColor3 = colors.bg,
		Parent = main,
	})

	local sidebar = Create("Frame", {
		Name = "Sidebar",
		Size = UDim2.new(0, M.sidebar, 1, 0),
		BackgroundColor3 = colors.chrome,
		Parent = body,
	}, {
		Create("Frame", {
			Name = "Border",
			AnchorPoint = Vector2.new(1, 0),
			Position = UDim2.fromScale(1, 0),
			Size = UDim2.new(0, 1, 1, 0),
			BackgroundColor3 = colors.border_soft,
			BorderSizePixel = 0,
		}),
	})

	-- Nav buttons live in their own frame so the sidebar's UIListLayout never
	-- tries to lay out the full-height Border hairline (which would otherwise
	-- consume the whole column and push the nav buttons off-screen).
	local nav = Create("Frame", {
		Name = "Nav",
		Size = UDim2.fromScale(1, 1),
		BackgroundTransparency = 1,
		Parent = sidebar,
	}, {
		Create.padding(16, 0),
		Create.listLayout({
			HorizontalAlignment = Enum.HorizontalAlignment.Center,
			Padding = UDim.new(0, 10),
		}),
	})

	local content = Create("ScrollingFrame", {
		Name = "Content",
		Position = UDim2.fromOffset(M.sidebar, 0),
		Size = UDim2.new(1, -M.sidebar, 1, 0),
		BackgroundTransparency = 1,
		BorderSizePixel = 0,
		CanvasSize = UDim2.new(),
		AutomaticCanvasSize = Enum.AutomaticSize.Y,
		ScrollBarThickness = 8,
		ScrollBarImageColor3 = Color3.fromHex("2A2A2E"),
		ScrollingDirection = Enum.ScrollingDirection.Y,
		Parent = body,
	}, {
		-- Vertical padding only. Horizontal insets are applied to each page
		-- explicitly (below) so column widths never depend on the executor's
		-- handling of scale-width children + scrollbar inside a ScrollingFrame.
		Create.padding(18, 0, 26, 0),
	})
	local CONTENT_PAD_X = 22

	-- ── status bar ───────────────────────────────────────────────────────────
	local status = Create("Frame", {
		Name = "StatusBar",
		AnchorPoint = Vector2.new(0, 1),
		Position = UDim2.fromScale(0, 1),
		Size = UDim2.new(1, 0, 0, M.statusbar),
		BackgroundColor3 = colors.chrome,
		Parent = main,
	}, {
		-- Round the bottom corners to match the window (see titlebar note).
		Create.corner(M.windowRadius),
		Create("Frame", { -- square off the top so only the bottom corners round
			Name = "SquareFill",
			Size = UDim2.new(1, 0, 0, M.windowRadius),
			BackgroundColor3 = colors.chrome,
			BorderSizePixel = 0,
		}),
		Create("Frame", {
			Name = "Border",
			Size = UDim2.new(1, 0, 0, 1),
			BackgroundColor3 = colors.border_soft,
			BorderSizePixel = 0,
		}),
		Create.padding(0, 22),
	})

	local clock = Create("TextLabel", {
		Name = "Clock",
		BackgroundTransparency = 1,
		Size = UDim2.fromScale(0.4, 1),
		Text = "—",
		TextColor3 = colors.text_muted,
		TextSize = 12,
		FontFace = Theme.Font.Regular,
		TextXAlignment = Enum.TextXAlignment.Left,
		Parent = status,
	})
	Create("TextLabel", {
		Name = "Subtitle",
		BackgroundTransparency = 1,
		Size = UDim2.fromScale(1, 1),
		Text = opts.Subtitle or "",
		TextColor3 = colors.text_muted,
		TextSize = 12,
		FontFace = Theme.Font.Regular,
		Parent = status,
	})
	Create("TextLabel", {
		Name = "Version",
		BackgroundTransparency = 1,
		AnchorPoint = Vector2.new(1, 0),
		Position = UDim2.fromScale(1, 0),
		Size = UDim2.fromScale(0.4, 1),
		Text = opts.Version or "",
		TextColor3 = colors.text_muted,
		TextSize = 12,
		FontFace = Theme.Font.Regular,
		TextXAlignment = Enum.TextXAlignment.Right,
		Parent = status,
	})

	-- live clock
	task.spawn(function()
		while clock.Parent do
			local t = os.date("*t")
			local h = t.hour % 12
			if h == 0 then
				h = 12
			end
			local ap = t.hour >= 12 and "PM" or "AM"
			clock.Text = ("%d:%02d %s"):format(h, t.min, ap)
			task.wait(10)
		end
	end)

	-- ── overlay (popovers + toasts) ──────────────────────────────────────────
	local overlay = Create("Frame", {
		Name = "Overlay",
		Size = UDim2.fromScale(1, 1),
		BackgroundTransparency = 1,
		ClipsDescendants = false,
		ZIndex = 100,
		Parent = main,
	})
	local toasts = Create("Frame", {
		Name = "Toasts",
		AnchorPoint = Vector2.new(1, 1),
		Position = UDim2.new(1, -16, 1, -46),
		Size = UDim2.fromOffset(260, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundTransparency = 1,
		Parent = overlay,
	}, {
		Create.listLayout({
			VerticalAlignment = Enum.VerticalAlignment.Bottom,
			HorizontalAlignment = Enum.HorizontalAlignment.Right,
			Padding = UDim.new(0, 9),
		}),
	})

	local ctx = Context.new(Theme, overlay, opts.Accent or colors.accent)

	-- logo follows accent
	ctx:RegisterAccent(function(accent, accentHover)
		logo.BackgroundColor3 = accent
		logoGradient.Color = ColorSequence.new(accentHover, accent)
	end)

	-- ── titlebar dragging ────────────────────────────────────────────────────
	local dragging, dragStart, startPos
	titlebar.InputBegan:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.MouseButton1
			or input.UserInputType == Enum.UserInputType.Touch then
			dragging = true
			dragStart = input.Position
			startPos = main.Position
		end
	end)
	UserInputService.InputChanged:Connect(function(input)
		if dragging and (input.UserInputType == Enum.UserInputType.MouseMovement
			or input.UserInputType == Enum.UserInputType.Touch) then
			local delta = input.Position - dragStart
			main.Position = UDim2.new(
				startPos.X.Scale, startPos.X.Offset + delta.X,
				startPos.Y.Scale, startPos.Y.Offset + delta.Y
			)
		end
	end)
	UserInputService.InputEnded:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.MouseButton1
			or input.UserInputType == Enum.UserInputType.Touch then
			dragging = false
		end
	end)

	-- ── public API ───────────────────────────────────────────────────────────
	local tabs = {}
	local activeIndex = 1
	local window = {}
	local applySearch -- forward declaration (used by select)

	local function currentQuery(): string
		return searchField.Visible and searchBox.Text or ""
	end

	local function select(index: number)
		activeIndex = index
		for i, tab in tabs do
			tab:_setActive(i == index)
		end
		content.CanvasPosition = Vector2.new(0, 0)
		applySearch(currentQuery()) -- keep the filter consistent across tabs
	end

	-- ── search ────────────────────────────────────────────────────────────────
	-- Concatenate every bit of text under an instance, lowercased, for matching.
	local function collectText(inst: Instance): string
		local parts = {}
		for _, d in inst:GetDescendants() do
			if (d:IsA("TextLabel") or d:IsA("TextButton") or d:IsA("TextBox")) and d.Text ~= "" then
				table.insert(parts, d.Text)
			end
		end
		return string.lower(table.concat(parts, " "))
	end

	-- Filter the active tab: show a group if its title matches, otherwise show
	-- only the fields whose text matches (hiding groups left with nothing).
	applySearch = function(query: string)
		query = string.lower(query or "")
		local tab = tabs[activeIndex]
		if not tab then
			return
		end
		for _, group in tab.page:GetDescendants() do
			if group:IsA("Frame") and group.Name == "Group" then
				local head = group:FindFirstChild("Head")
				local card = group:FindFirstChild("Card")
				local titleLabel = head and head:FindFirstChild("Title")
				local titleText = (titleLabel and titleLabel:IsA("TextLabel"))
					and string.lower(titleLabel.Text) or ""
				local groupMatch = query == "" or string.find(titleText, query, 1, true) ~= nil

				local anyVisible = false
				if card then
					for _, item in card:GetChildren() do
						if item:IsA("GuiObject") and item.Name ~= "Separator" then
							local matches = groupMatch
								or string.find(collectText(item), query, 1, true) ~= nil
							item.Visible = matches
							if matches then
								anyVisible = true
							end
						end
					end
				end
				group.Visible = query == "" or groupMatch or anyVisible
			end
		end
	end

	searchBox:GetPropertyChangedSignal("Text"):Connect(function()
		applySearch(searchBox.Text)
	end)
	winBtns.search.Activated:Connect(function()
		searchField.Visible = not searchField.Visible
		if searchField.Visible then
			searchBox:CaptureFocus()
		else
			searchBox.Text = "" -- fires the Text signal → clears the filter
		end
	end)

	-- ── minimize / restore (RightShift) ────────────────────────────────────────
	local restoreHint = Create("Frame", {
		Name = "MinimizedHint",
		Visible = false,
		AnchorPoint = Vector2.new(1, 1),
		Position = UDim2.new(1, -16, 1, -16),
		Size = UDim2.fromOffset(220, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		BackgroundColor3 = colors.pop,
		Parent = screenGui,
	}, {
		Create.corner(9),
		Create.stroke(colors.border),
		Create.padding(11, 14),
		Create.listLayout({ Padding = UDim.new(0, 3) }),
	})
	Create("TextLabel", {
		Name = "Title",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		Text = "UI Minimized",
		TextColor3 = colors.text,
		TextSize = 13,
		FontFace = Theme.Font.Medium,
		TextXAlignment = Enum.TextXAlignment.Left,
		LayoutOrder = 1,
		Parent = restoreHint,
	})
	Create("TextLabel", {
		Name = "Text",
		BackgroundTransparency = 1,
		Size = UDim2.new(1, 0, 0, 0),
		AutomaticSize = Enum.AutomaticSize.Y,
		Text = "Press RightShift to show it again.",
		TextColor3 = colors.text_muted,
		TextSize = 12,
		FontFace = Theme.Font.Regular,
		TextXAlignment = Enum.TextXAlignment.Left,
		TextWrapped = true,
		LayoutOrder = 2,
		Parent = restoreHint,
	})

	local minimized = false
	local function setMinimized(value: boolean)
		minimized = value
		if value then
			-- shrink + fade the whole window away together, then hide it once the
			-- fade has fully played (no abrupt cut — it's already invisible).
			Tween.play(mainScale, Tween.MenuOut, { Scale = 0.9 })
			Tween.play(shadow, Tween.MenuOut, { ImageTransparency = 1 })
			local t = Tween.play(main, Tween.MenuOut, { GroupTransparency = 1 })
			t.Completed:Once(function()
				if minimized then
					main.Visible = false
				end
			end)
			restoreHint.Visible = true
		else
			-- restore from the shrunk/faded state: pop the scale, ease the fade in
			main.Visible = true
			mainScale.Scale = 0.9
			main.GroupTransparency = 1
			Tween.play(mainScale, Tween.Pop, { Scale = 1 })
			Tween.play(main, Tween.Normal, { GroupTransparency = 0 })
			Tween.play(shadow, Tween.Normal, { ImageTransparency = SHADOW_T })
			restoreHint.Visible = false
		end
	end
	winBtns.min.Activated:Connect(function()
		setMinimized(true)
	end)
	UserInputService.InputBegan:Connect(function(input)
		if minimized and input.KeyCode == Enum.KeyCode.RightShift then
			setMinimized(false)
		end
	end)

	-- ── maximize toggle ─────────────────────────────────────────────────────────
	local maximized = false
	winBtns.max.Activated:Connect(function()
		maximized = not maximized
		if maximized then
			local vp = screenGui.AbsoluteSize
			Tween.play(main, Tween.Normal, {
				Size = UDim2.fromOffset(
					math.max(M.windowWidth, vp.X - 24),
					math.max(M.windowHeight, vp.Y - 24)
				),
			})
		else
			local vp = screenGui.AbsoluteSize
			Tween.play(main, Tween.Normal, {
				Size = UDim2.fromOffset(
					math.min(M.windowWidth, vp.X - 24),
					math.min(M.windowHeight, vp.Y - 24)
				),
			})
		end
	end)

	-- ── close ────────────────────────────────────────────────────────────────
	winBtns.close.Activated:Connect(function()
		-- same shrink+fade as minimize, but disable the gui once it's gone
		Tween.play(mainScale, Tween.MenuOut, { Scale = 0.9 })
		Tween.play(shadow, Tween.MenuOut, { ImageTransparency = 1 })
		local t = Tween.play(main, Tween.MenuOut, { GroupTransparency = 1 })
		t.Completed:Once(function()
			screenGui.Enabled = false
			mainScale.Scale = 1 -- reset in case it's ever re-enabled
			main.GroupTransparency = 0
			shadow.ImageTransparency = SHADOW_T
		end)
	end)

	function window:CreateTab(tabOpts: any)
		local tab = Tab(ctx, tabOpts or {})
		tab.button.Parent = nav
		tab.page.Parent = content

		-- Inset the page explicitly and size it to the scroll area's *visible*
		-- width (AbsoluteWindowSize excludes the scrollbar). This guarantees the
		-- right column keeps its margin regardless of executor quirks.
		tab.page.Position = UDim2.fromOffset(CONTENT_PAD_X, 0)
		local function fitPage()
			local avail = content.AbsoluteWindowSize.X
			if avail <= 0 then
				avail = content.AbsoluteSize.X
			end
			tab.page.Size = UDim2.new(0, math.max(0, avail - CONTENT_PAD_X * 2), 0, 0)
		end
		content:GetPropertyChangedSignal("AbsoluteSize"):Connect(fitPage)
		content:GetPropertyChangedSignal("AbsoluteWindowSize"):Connect(fitPage)
		task.defer(fitPage)

		local index = #tabs + 1
		tab.button.LayoutOrder = index
		table.insert(tabs, tab)
		tab.button.Activated:Connect(function()
			select(index)
		end)
		if index == 1 then
			select(1)
		end
		return tab
	end

	function window:Select(index: number)
		select(index)
	end

	function window:Notify(notifyOpts: any)
		Notify(ctx, toasts, notifyOpts)
	end

	function window:SetAccent(color: Color3)
		ctx:SetAccent(color)
	end

	-- mount — pop the window in from a touch smaller and faded so it eases in
	-- rather than just appearing
	mainScale.Scale = 0.92
	main.GroupTransparency = 1
	syncShadow()
	task.defer(function()
		Tween.play(mainScale, Tween.Pop, { Scale = 1 })
		Tween.play(main, Tween.Normal, { GroupTransparency = 0 })
		Tween.play(shadow, Tween.Normal, { ImageTransparency = SHADOW_T })
	end)

	local localPlayer = Players.LocalPlayer
	if localPlayer then
		screenGui.Parent = localPlayer:WaitForChild("PlayerGui")
	elseif RunService:IsStudio() then
		screenGui.Parent = game:GetService("CoreGui")
	end

	return window
end

end

__modules['util.Context'] = function()
--!strict
-- util/Context.lua — the object threaded through every component.
--
-- Carries the live accent color (themeable via Window:SetAccent), an accent
-- subscription registry, and the single-popover manager used by dropdowns and
-- color pickers (menus mount into a high-ZIndex overlay so they escape the
-- scrolling content's clipping).

local Create = __require("util.Create")
local Tween = __require("util.Tween")

local Context = {}
Context.__index = Context

export type Context = typeof(setmetatable(
	{} :: {
		Theme: any,
		Accent: Color3,
		AccentHover: Color3,
		overlay: Frame,
		_consumers: { (Color3, Color3) -> () },
		_popover: { menu: Instance, catcher: Instance, conns: { RBXScriptConnection }, onClose: (() -> ())? }?,
	},
	Context
))

local function hover(accent: Color3): Color3
	return accent:Lerp(Color3.new(1, 1, 1), 0.3)
end

function Context.new(theme: any, overlay: Frame, accent: Color3): Context
	return setmetatable({
		Theme = theme,
		Accent = accent,
		AccentHover = hover(accent),
		overlay = overlay,
		_consumers = {},
		_popover = nil,
	}, Context)
end

-- Register a function recolored whenever the accent changes. Called once now
-- with the current accent so callers don't duplicate the initial paint.
function Context:RegisterAccent(fn: (Color3, Color3) -> ())
	table.insert(self._consumers, fn)
	fn(self.Accent, self.AccentHover)
end

function Context:SetAccent(color: Color3)
	self.Accent = color
	self.AccentHover = hover(color)
	for _, fn in self._consumers do
		fn(self.Accent, self.AccentHover)
	end
end

-- ── Popovers ───────────────────────────────────────────────────────────────
function Context:ClosePopover()
	local p = self._popover
	if not p then
		return
	end
	self._popover = nil
	for _, conn in p.conns do
		conn:Disconnect()
	end
	p.catcher:Destroy()
	p.menu.Visible = false
	if p.onClose then
		p.onClose()
	end
end

-- Open `menu` directly under `anchor`, closing any other open popover first.
-- A full-overlay catcher button dismisses it on any outside click.
function Context:OpenPopover(menu: GuiObject, anchor: GuiObject, onClose: (() -> ())?)
	self:ClosePopover()

	local catcher = Create("TextButton", {
		Name = "Catcher",
		Size = UDim2.fromScale(1, 1),
		BackgroundTransparency = 1,
		Text = "",
		AutoButtonColor = false,
		ZIndex = 50,
		Parent = self.overlay,
	})
	menu.ZIndex = 60
	menu.Parent = self.overlay

	-- Place the menu under the anchor, but keep it inside the overlay (= window)
	-- bounds: clamp horizontally, and flip above the anchor when there isn't
	-- enough room below. The window clips descendants, so a menu that spilled
	-- off the edge would be cut off — this keeps it fully visible.
	local MARGIN = 8
	local GAP = 6
	local function place()
		local o = self.overlay.AbsolutePosition
		local os = self.overlay.AbsoluteSize
		local a = anchor.AbsolutePosition
		local asz = anchor.AbsoluteSize
		local msz = menu.AbsoluteSize

		local x = a.X - o.X
		x = math.clamp(x, MARGIN, math.max(MARGIN, os.X - msz.X - MARGIN))

		local below = (a.Y - o.Y) + asz.Y + GAP
		local above = (a.Y - o.Y) - msz.Y - GAP
		local y = below
		if below + msz.Y > os.Y - MARGIN and above >= MARGIN then
			y = above -- not enough room below → open upward
		end
		y = math.clamp(y, MARGIN, math.max(MARGIN, os.Y - msz.Y - MARGIN))

		menu.Position = UDim2.fromOffset(x, y)
	end
	place()
	menu.Visible = true

	-- Fade the menu in. CanvasGroup renders its descendants to one buffer, so a
	-- single GroupTransparency tween brings the whole popover up together.
	if menu:IsA("CanvasGroup") then
		menu.GroupTransparency = 1
		Tween.play(menu, Tween.Pop, { GroupTransparency = 0 })
	end

	-- Re-place when the anchor moves, when the menu's auto-size settles, or when
	-- the window resizes.
	local conns = {
		anchor:GetPropertyChangedSignal("AbsolutePosition"):Connect(place),
		menu:GetPropertyChangedSignal("AbsoluteSize"):Connect(place),
		self.overlay:GetPropertyChangedSignal("AbsoluteSize"):Connect(place),
	}
	self._popover = { menu = menu, catcher = catcher, conns = conns, onClose = onClose }
	catcher.Activated:Connect(function()
		self:ClosePopover()
	end)
end

function Context:IsOpen(menu: GuiObject): boolean
	return self._popover ~= nil and self._popover.menu == menu
end

return Context

end

__modules['util.Create'] = function()
--!strict
-- util/Create.lua — tiny instance factory + common UI helpers.
--
--   Create("Frame", { Size = ..., Parent = ... }, { childA, childB })
--
-- Props are assigned in order; `Parent` is always applied last so children
-- exist before the instance enters the tree. Helper constructors (corner,
-- stroke, padding, listLayout) cover the boilerplate instances used everywhere.

local Create = setmetatable({}, {
	__call = function(_, className: string, props: { [string]: any }?, children: { Instance }?): any
		local inst = Instance.new(className)
		local parent
		if props then
			for key, value in props do
				if key == "Parent" then
					parent = value
				else
					(inst :: any)[key] = value
				end
			end
		end
		if children then
			for _, child in children do
				child.Parent = inst
			end
		end
		inst.Parent = parent
		return inst
	end,
})

function Create.corner(radius: number): UICorner
	return Create("UICorner", { CornerRadius = UDim.new(0, radius) })
end

function Create.stroke(color: Color3, thickness: number?): UIStroke
	return Create("UIStroke", {
		Color = color,
		Thickness = thickness or 1,
		ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
		-- Round joins trace the UICorner arc smoothly instead of cutting it with
		-- mitred corners, which is what made bordered cards/controls look jagged.
		LineJoinMode = Enum.LineJoinMode.Round,
	})
end

function Create.padding(top: number, right: number?, bottom: number?, left: number?): UIPadding
	right = right or top
	bottom = bottom or top
	left = left or right
	return Create("UIPadding", {
		PaddingTop = UDim.new(0, top),
		PaddingRight = UDim.new(0, right),
		PaddingBottom = UDim.new(0, bottom),
		PaddingLeft = UDim.new(0, left),
	})
end

function Create.listLayout(props: { [string]: any }?): UIListLayout
	local layout = Create("UIListLayout", {
		SortOrder = Enum.SortOrder.LayoutOrder,
		FillDirection = Enum.FillDirection.Vertical,
	})
	if props then
		for key, value in props do
			(layout :: any)[key] = value
		end
	end
	return layout
end

return Create

end

__modules['util.Tween'] = function()
--!strict
-- util/Tween.lua — shared tween presets. All UI motion is ease-out ~0.12–0.18s.

local TweenService = game:GetService("TweenService")

local Tween = {}

local OUT = Enum.EasingStyle.Quad
local DIR = Enum.EasingDirection.Out

Tween.Fast   = TweenInfo.new(0.12, OUT, DIR) -- hovers, borders
Tween.Normal = TweenInfo.new(0.18, OUT, DIR) -- toggle, chevron
Tween.Spin   = TweenInfo.new(0.26, Enum.EasingStyle.Back, DIR) -- collapse chevrons (slight overshoot)
Tween.Spring = TweenInfo.new(0.28, Enum.EasingStyle.Back, DIR) -- knobs / pops that should overshoot
Tween.Press  = TweenInfo.new(0.09, Enum.EasingStyle.Quad, DIR) -- button tap squash
Tween.Pop    = TweenInfo.new(0.16, Enum.EasingStyle.Back, DIR) -- popovers / window in
Tween.MenuOut = TweenInfo.new(0.2, Enum.EasingStyle.Quad, Enum.EasingDirection.In) -- window leaving (accelerate + fade away)
Tween.Toast  = TweenInfo.new(0.22, Enum.EasingStyle.Quint, DIR)
Tween.ToastOut = TweenInfo.new(0.25, Enum.EasingStyle.Quad, Enum.EasingDirection.In)

function Tween.play(instance: Instance, info: TweenInfo, goals: { [string]: any }): Tween
	local tween = TweenService:Create(instance, info, goals)
	tween:Play()
	return tween
end

return Tween

end

return __require("")