-- Uranium status page (standalone) — generated by bundle.py from
-- coreui/components/Screen.lua + standalone/screen.prelude.lua.
-- Do not edit by hand; edit those two and rebuild.
-- build: 2026-08-15 04:28:41 24b4365
-- The chunk's value is the function: show(opts) -> handle.
local passed = ...
local CACHE: any = type(passed) == "table" and passed or nil
local function service(name: string): any
if CACHE then
local okCache, cached = pcall(function()
return CACHE[name]
end)
if okCache and cached then
return cached
end
end
local ok, svc = pcall(function()
local s = game:GetService(name)
return (type(cloneref) == "function") and cloneref(s) or s
end)
return ok and svc or nil
end
local UIS = service("UserInputService")
local TS = service("TweenService")
local C = {accent=Color3.fromHex("7BE04A"),accent_fill=Color3.fromHex("5EB832"),border=Color3.fromHex("2B3427"),border_soft=Color3.fromHex("1F271D"),card=Color3.fromHex("171D15"),chrome=Color3.fromHex("0B0F0A"),control=Color3.fromHex("1D241B"),control_hi=Color3.fromHex("262E23"),danger=Color3.fromHex("FF6B6B"),knockout=Color3.fromHex("08140A"),text=Color3.fromHex("E9F2E5"),text_dim=Color3.fromHex("616D5D"),text_muted=Color3.fromHex("98A394"),warning=Color3.fromHex("FFC53D")}
local GOTHAM = "rbxasset://fonts/families/GothamSSm.json"
local F = {
Bold = Font.new(GOTHAM, Enum.FontWeight.Bold),
Medium = Font.new(GOTHAM, Enum.FontWeight.Medium),
Regular = Font.new(GOTHAM, Enum.FontWeight.Regular),
Mono = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular),
}
local function new(className: string, props: any?, children: any?): any
local inst = Instance.new(className)
local parent
if props then
for key, value in pairs(props) do
if key == "Parent" then
parent = value
else
(inst :: any)[key] = value
end
end
end
if children then
for _, child in ipairs(children) do
child.Parent = inst
end
end
inst.Parent = parent
return inst
end
local function corner(radius: number): any
return new("UICorner", { CornerRadius = UDim.new(0, radius) })
end
local function stroke(color: any, thickness: number?): any
return new("UIStroke", {
Color = color,
Thickness = thickness or 1,
ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
LineJoinMode = Enum.LineJoinMode.Round,
})
end
local function pad(top: number, right: number?, bottom: number?, left: number?): any
right = right or top
bottom = bottom or top
left = left or right
return new("UIPadding", {
PaddingTop = UDim.new(0, top),
PaddingRight = UDim.new(0, right),
PaddingBottom = UDim.new(0, bottom),
PaddingLeft = UDim.new(0, left),
})
end
local function list(props: any?): any
local layout = new("UIListLayout", {
SortOrder = Enum.SortOrder.LayoutOrder,
FillDirection = Enum.FillDirection.Vertical,
})
if props then
for key, value in pairs(props) do
(layout :: any)[key] = value
end
end
return layout
end
local OUT = Enum.EasingDirection.Out
local QUAD = Enum.EasingStyle.Quad
local TW = {
Fast = TweenInfo.new(0.12, QUAD, OUT),
Normal = TweenInfo.new(0.18, QUAD, OUT),
Pop = TweenInfo.new(0.16, Enum.EasingStyle.Back, OUT),
MenuOut = TweenInfo.new(0.2, QUAD, Enum.EasingDirection.In),
}
local function tw(inst: any, info: any, goals: any): any
if not TS then
for key, value in pairs(goals) do
inst[key] = value
end
return nil
end
local tween = TS:Create(inst, info, goals)
tween:Play()
return tween
end
local ICONS = {["ban"]={16898612629,{48,48},{196,967}},["download"]={16898613044,{48,48},{820,906}},["message-circle"]={16898613613,{48,48},{563,820}},["octagon-alert"]={16898613613,{48,48},{918,404}},["package"]={16898613613,{48,48},{918,196}},["pause"]={16898613699,{48,48},{0,771}},["refresh-cw"]={16898613699,{48,48},{404,869}},["triangle-alert"]={16898613869,{48,48},{967,0}},["wrench"]={16898613869,{48,48},{820,906}},["x"]={16898613869,{48,48},{869,906}}}
local function newIcon(name: string, size: number, color: any): any
local entry = ICONS[name]
if entry then
return new("ImageLabel", {
Name = "Icon",
BackgroundTransparency = 1,
Size = UDim2.fromOffset(size, size),
Image = "rbxassetid://" .. entry[1],
ImageRectSize = Vector2.new(entry[2][1], entry[2][2]),
ImageRectOffset = Vector2.new(entry[3][1], entry[3][2]),
ImageColor3 = color,
ScaleType = Enum.ScaleType.Stretch,
})
end
return new("TextLabel", {
Name = "Icon",
BackgroundTransparency = 1,
Size = UDim2.fromOffset(size, size),
Text = "•",
TextColor3 = color,
TextSize = size,
FontFace = F.Medium,
})
end
local function tintIcon(icon: any, color: any)
if icon:IsA("ImageLabel") then
icon.ImageColor3 = color
elseif icon:IsA("TextLabel") then
icon.TextColor3 = color
end
end
local function newFade(root: any): any
local self: any = {}
local targets: any = nil
local driver: any, conn: any = nil, nil
local alpha = 0
local function collect(inst: any, out: any)
if inst:IsA("GuiObject") then
table.insert(out, { inst, "BackgroundTransparency", inst.BackgroundTransparency })
if inst:IsA("TextLabel") or inst:IsA("TextButton") or inst:IsA("TextBox") then
table.insert(out, { inst, "TextTransparency", inst.TextTransparency })
end
if inst:IsA("ImageLabel") or inst:IsA("ImageButton") then
table.insert(out, { inst, "ImageTransparency", inst.ImageTransparency })
end
if inst:IsA("ScrollingFrame") then
table.insert(out, { inst, "ScrollBarImageTransparency", inst.ScrollBarImageTransparency })
end
elseif inst:IsA("UIStroke") then
table.insert(out, { inst, "Transparency", inst.Transparency })
end
for _, child in ipairs(inst:GetChildren()) do
if not (child:IsA("GuiObject") and not child.Visible) then
collect(child, out)
end
end
end
local function snapshot()
if targets then
return
end
targets = {}
collect(root, targets)
end
local function put(a: number)
alpha = a
if not targets then
return
end
for _, t in ipairs(targets) do
t[1][t[2]] = t[3] + (1 - t[3]) * a
end
end
local function stop()
if conn then
conn:Disconnect()
conn = nil
end
if driver then
driver:Destroy()
driver = nil
end
end
local function land(a: number, done: any)
stop()
put(a)
if a <= 0 then
targets = nil
end
if done then
done()
end
end
function self:Set(a: number)
stop()
snapshot()
put(a)
if a <= 0 then
targets = nil
end
end
function self:To(info: any, a: number, done: any)
stop()
snapshot()
local value = Instance.new("NumberValue")
value.Value = alpha
driver = value
conn = value.Changed:Connect(put)
local tween = tw(value, info, { Value = a })
if not tween then
land(a, done)
return
end
tween.Completed:Once(function()
if driver ~= value then
return
end
land(a, done)
end)
end
function self:Destroy()
stop()
targets = nil
end
return self
end
local ATTR = "__urn"
local ALPHA = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
local function gname(): string
local out = {}
for i = 1, 12 do
local n = math.random(1, #ALPHA)
out[i] = string.sub(ALPHA, n, n)
end
return table.concat(out)
end
local function mountGui(gui: any, preferred: any)
pcall(function()
gui:SetAttribute(ATTR, true)
end)
pcall(function()
if type(protect_gui) == "function" then
protect_gui(gui)
elseif type(syn) == "table" and type(syn.protect_gui) == "function" then
syn.protect_gui(gui)
end
end)
local targets = {}
if typeof(preferred) == "Instance" then
table.insert(targets, preferred)
end
pcall(function()
if type(gethui) == "function" then
local hidden = gethui()
if typeof(hidden) == "Instance" then
table.insert(targets, hidden)
end
end
end)
local core = service("CoreGui")
if core then
table.insert(targets, core)
end
pcall(function()
local players = service("Players")
local player = players and players.LocalPlayer
if player then
local pg = player:FindFirstChildOfClass("PlayerGui") or player:WaitForChild("PlayerGui", 5)
if pg then
table.insert(targets, pg)
end
end
end)
for _, target in ipairs(targets) do
local ok = pcall(function()
gui.Parent = target
end)
if ok and gui.Parent == target then
return
end
end
end
local ORDER = 1000000 -- above the window's ScreenGui, which leaves DisplayOrder at 0
local DIM = 0.28      -- backdrop transparency at rest (lower = darker)
local CARD_W = 420    -- max card width; below that it tracks the viewport
local PAD = 18
local GAP = 12
local RADIUS = 14
local function str(v: any): string?
if type(v) == "string" then
return v ~= "" and v or nil
end
if type(v) == "number" then
return tostring(v)
end
return nil
end
local function toneOf(v: any): Color3
local name = type(v) == "string" and string.lower(v) or ""
if name == "warning" or name == "warn" then
return C.warning
elseif name == "info" then
return C.accent
end
return C.danger
end
local function copyText(text: string): boolean
local fn: any = nil
pcall(function()
if type(setclipboard) == "function" then
fn = setclipboard
elseif type(toclipboard) == "function" then
fn = toclipboard
end
end)
if not fn then
return false
end
return (pcall(fn, text))
end
local function putIcon(parent: Instance, name: string, size: number, color: Color3): any
local i: any = newIcon(name, size, color)
i.AnchorPoint = Vector2.new(0.5, 0.5)
i.Position = UDim2.fromScale(0.5, 0.5)
i.Parent = parent
return i
end
local active: any = nil
return function(opts: any): any
local o: any = {}
if type(opts) == "table" then
for key, value in opts :: any do
o[key] = value
end
end
if active then
local previous = active
active = nil
previous:Close(true)
end
local dismissable = o.Dismissable ~= false
local tone = toneOf(o.Tone)
local screenGui = new("ScreenGui", {
Name = gname(),
DisplayOrder = ORDER,
IgnoreGuiInset = true,
ResetOnSpawn = false,
ZIndexBehavior = Enum.ZIndexBehavior.Sibling,
})
local backdrop = new("TextButton", {
Name = "Backdrop",
AutoButtonColor = false,
Modal = true,
Text = "",
Size = UDim2.fromScale(1, 1),
BackgroundColor3 = C.chrome,
BackgroundTransparency = DIM,
BorderSizePixel = 0,
Parent = screenGui,
})
local card = new("Frame", {
Name = "Card",
AnchorPoint = Vector2.new(0.5, 0.5),
Position = UDim2.fromScale(0.5, 0.5),
Size = UDim2.new(0.92, 0, 0, 0),
AutomaticSize = Enum.AutomaticSize.Y,
BackgroundColor3 = C.card,
Parent = backdrop,
}, {
corner(RADIUS),
stroke(C.border),
pad(PAD),
list({ Padding = UDim.new(0, GAP) }),
new("UISizeConstraint", { MaxSize = Vector2.new(CARD_W, math.huge) }),
})
local scale = new("UIScale", { Parent = card })
local head = new("Frame", {
Name = "Head",
BackgroundTransparency = 1,
Size = UDim2.new(1, 0, 0, 40),
LayoutOrder = 1,
Parent = card,
})
local chip = new("Frame", {
Name = "Chip",
Size = UDim2.fromOffset(40, 40),
BackgroundColor3 = C.card:Lerp(tone, 0.16),
Parent = head,
}, {
corner(12),
})
local iconName = str(o.Icon) or "triangle-alert"
local iconInst = putIcon(chip, iconName, 20, tone)
local closeBtn = new("TextButton", {
Name = "Close",
AutoButtonColor = false,
Text = "",
BackgroundTransparency = 1,
AnchorPoint = Vector2.new(1, 0.5),
Position = UDim2.new(1, 0, 0.5, 0),
Size = UDim2.fromOffset(24, 24),
Visible = dismissable,
Parent = head,
})
local closeIcon = putIcon(closeBtn, "x", 16, C.text_dim)
closeBtn.MouseEnter:Connect(function()
tintIcon(closeIcon, C.text)
end)
closeBtn.MouseLeave:Connect(function()
tintIcon(closeIcon, C.text_dim)
end)
local titleBlock = new("Frame", {
Name = "TitleBlock",
BackgroundTransparency = 1,
Size = UDim2.new(1, 0, 0, 0),
AutomaticSize = Enum.AutomaticSize.Y,
LayoutOrder = 2,
Parent = card,
}, {
list({ Padding = UDim.new(0, 4) }),
})
local title = new("TextLabel", {
Name = "Title",
BackgroundTransparency = 1,
Size = UDim2.new(1, 0, 0, 0),
AutomaticSize = Enum.AutomaticSize.Y,
Text = "",
TextColor3 = C.text,
TextSize = 18,
FontFace = F.Bold,
TextXAlignment = Enum.TextXAlignment.Left,
TextWrapped = true,
LayoutOrder = 1,
Parent = titleBlock,
})
local codeLabel = new("TextLabel", {
Name = "Code",
BackgroundTransparency = 1,
Size = UDim2.new(1, 0, 0, 0),
AutomaticSize = Enum.AutomaticSize.Y,
Text = "",
TextColor3 = C.text_dim,
TextSize = 11,
FontFace = F.Mono,
TextXAlignment = Enum.TextXAlignment.Left,
TextWrapped = true,
Visible = false,
LayoutOrder = 2,
Parent = titleBlock,
})
local rule = new("Frame", {
Name = "Rule",
Size = UDim2.new(1, 0, 0, 1),
BackgroundColor3 = tone,
BackgroundTransparency = 0.45,
BorderSizePixel = 0,
LayoutOrder = 3,
Parent = card,
})
local body = new("TextLabel", {
Name = "Text",
BackgroundTransparency = 1,
Size = UDim2.new(1, 0, 0, 0),
AutomaticSize = Enum.AutomaticSize.Y,
Text = "",
TextColor3 = C.text_muted,
TextSize = 13,
FontFace = F.Regular,
TextXAlignment = Enum.TextXAlignment.Left,
TextYAlignment = Enum.TextYAlignment.Top,
TextWrapped = true,
LineHeight = 1.25,
Visible = false,
LayoutOrder = 4,
Parent = card,
})
local inviteRow = new("Frame", {
Name = "Discord",
Size = UDim2.new(1, 0, 0, 32),
BackgroundColor3 = C.control,
Visible = false,
LayoutOrder = 5,
Parent = card,
}, {
corner(8),
stroke(C.border),
})
local inviteIcon: any = newIcon("message-circle", 14, C.text_dim)
inviteIcon.AnchorPoint = Vector2.new(0, 0.5)
inviteIcon.Position = UDim2.new(0, 11, 0.5, 0)
inviteIcon.Parent = inviteRow
local inviteBox = new("TextBox", {
Name = "Invite",
BackgroundTransparency = 1,
Position = UDim2.fromOffset(33, 0),
Size = UDim2.new(1, -44, 1, 0),
Text = "",
TextColor3 = C.text,
TextSize = 12,
FontFace = F.Mono,
TextXAlignment = Enum.TextXAlignment.Left,
ClearTextOnFocus = false,
TextEditable = false,
Parent = inviteRow,
})
local actions = new("Frame", {
Name = "Actions",
BackgroundTransparency = 1,
Size = UDim2.new(1, 0, 0, 34),
Visible = false,
LayoutOrder = 8,
Parent = card,
}, {
list({
FillDirection = Enum.FillDirection.Horizontal,
VerticalAlignment = Enum.VerticalAlignment.Center,
Padding = UDim.new(0, 8),
}),
})
local flash = new("TextLabel", {
Name = "Flash",
BackgroundTransparency = 1,
Size = UDim2.new(1, 0, 0, 14),
Text = "",
TextColor3 = C.accent,
TextSize = 11,
FontFace = F.Regular,
TextXAlignment = Enum.TextXAlignment.Left,
TextTransparency = 1,
TextTruncate = Enum.TextTruncate.AtEnd,
Visible = false,
LayoutOrder = 9,
Parent = card,
})
local footerRule = new("Frame", {
Name = "FooterRule",
Size = UDim2.new(1, 0, 0, 1),
BackgroundColor3 = C.border_soft,
BorderSizePixel = 0,
Visible = false,
LayoutOrder = 10,
Parent = card,
})
local footer = new("TextLabel", {
Name = "Footer",
BackgroundTransparency = 1,
Size = UDim2.new(1, 0, 0, 0),
AutomaticSize = Enum.AutomaticSize.Y,
Text = "",
TextColor3 = C.text_dim,
TextSize = 11,
FontFace = F.Regular,
TextXAlignment = Enum.TextXAlignment.Left,
TextWrapped = true,
Visible = false,
LayoutOrder = 11,
Parent = card,
})
local handle: any = {}
handle.ScreenGui = screenGui
handle.Card = card
local fade = newFade(backdrop)
local closing = false
local conns: { RBXScriptConnection } = {}
local flashToken = 0
function handle:Close(immediate: boolean?)
if closing then
return
end
closing = true
if active == handle then
active = nil
end
if immediate then
screenGui:Destroy()
return
end
tw(scale, TW.MenuOut, { Scale = 0.96 })
fade:To(TW.MenuOut, 1, function()
screenGui:Destroy()
end)
end
screenGui.Destroying:Connect(function()
closing = true
if active == handle then
active = nil
end
for _, conn in conns do
conn:Disconnect()
end
table.clear(conns)
fade:Destroy()
end)
function handle:Flash(text: any)
local s = str(text)
flash.Text = s or ""
flash.Visible = s ~= nil
if not s then
flash.TextTransparency = 1
return
end
flashToken += 1
local token = flashToken
tw(flash, TW.Fast, { TextTransparency = 0 })
task.delay(3, function()
if closing or token ~= flashToken then
return
end
tw(flash, TW.Normal, { TextTransparency = 1 })
end)
end
local function newButton(label: string, icon: string?, primary: boolean, onClick: () -> ()): any
local base = primary and C.accent_fill or C.control
local over = primary and C.accent or C.control_hi
local btn = new("TextButton", {
Name = "Action",
AutoButtonColor = false,
AutomaticSize = Enum.AutomaticSize.X,
Size = UDim2.fromOffset(0, 34),
BackgroundColor3 = base,
Text = label,
TextColor3 = primary and C.knockout or C.text,
TextSize = 13,
FontFace = F.Medium,
Parent = actions,
}, {
corner(8),
pad(0, 14, 0, icon and 32 or 14),
new("UISizeConstraint", { MinSize = Vector2.new(76, 34) }),
})
if icon then
local bi: any = newIcon(icon, 14, primary and C.knockout or C.text_muted)
bi.AnchorPoint = Vector2.new(0, 0.5)
bi.Position = UDim2.new(0, 11, 0.5, 0)
bi.Parent = btn
end
btn.MouseEnter:Connect(function()
tw(btn, TW.Fast, { BackgroundColor3 = over })
end)
btn.MouseLeave:Connect(function()
tw(btn, TW.Fast, { BackgroundColor3 = base })
end)
btn.Activated:Connect(onClick)
return btn
end
local function buildActions()
for _, child in actions:GetChildren() do
if child:IsA("GuiObject") then
child:Destroy()
end
end
local n = 0
if type(o.Actions) == "table" then
for _, def in o.Actions :: any do
if type(def) == "table" then
local closeAfter = def.Close ~= false
local callback = type(def.Callback) == "function" and def.Callback or nil
local btn = newButton(str(def.Label) or "OK", str(def.Icon), def.Primary == true, function()
if callback then
task.spawn(function()
pcall(callback, handle)
end)
end
if closeAfter then
handle:Close()
end
end)
n += 1
btn.LayoutOrder = n
end
end
end
local invite = str(o.Discord)
if invite then
local only = n == 0
n += 1
local btn = newButton("Copy Discord", "message-circle", only, function()
if copyText(invite) then
handle:Flash("Copied " .. invite)
else
handle:Flash("No clipboard here — select the invite above.")
end
end)
btn.LayoutOrder = n
end
actions.Visible = n > 0
end
local function apply(patch: any?)
if patch ~= nil then
if type(patch) ~= "table" then
return
end
for key, value in patch :: any do
o[key] = value
end
end
dismissable = o.Dismissable ~= false
closeBtn.Visible = dismissable
tone = toneOf(o.Tone)
chip.BackgroundColor3 = C.card:Lerp(tone, 0.16)
rule.BackgroundColor3 = tone
local nextIcon = str(o.Icon) or "triangle-alert"
if nextIcon ~= iconName then
iconName = nextIcon
iconInst:Destroy()
iconInst = putIcon(chip, iconName, 20, tone)
else
tintIcon(iconInst, tone)
end
title.Text = str(o.Title) or "Something went wrong"
local code = str(o.Code)
codeLabel.Text = code or ""
codeLabel.Visible = code ~= nil
local text = str(o.Text)
body.Text = text or ""
body.Visible = text ~= nil
local invite = str(o.Discord)
inviteBox.Text = invite or ""
inviteRow.Visible = invite ~= nil
local foot = str(o.Footer)
footer.Text = foot or ""
footer.Visible = foot ~= nil
footerRule.Visible = foot ~= nil
buildActions()
end
function handle:Set(patch: any)
if closing then
return
end
apply(patch or {})
end
closeBtn.Activated:Connect(function()
if dismissable then
handle:Close()
end
end)
if UIS then
table.insert(conns, UIS.InputBegan:Connect(function(input, gameProcessed)
if gameProcessed or not dismissable or closing then
return
end
if input.KeyCode == Enum.KeyCode.Escape then
handle:Close()
end
end))
end
apply(nil)
mountGui(screenGui, typeof(o.Parent) == "Instance" and o.Parent or nil)
fade:Set(1)
scale.Scale = 0.94
tw(scale, TW.Pop, { Scale = 1 })
fade:To(TW.Normal, 0)
active = handle
return handle
end
